// RGB adaptation of PBRT v4's null-scattering path-space MIS estimator.
// https://pbr-book.org/4ed/Light_Transport_II_Volume_Rendering/Volume_Scattering_Integrators
#include "volpath.h"
#include "boundary.h"
#include <algorithm>
#include <limits>
#include <stdexcept>


// Shared machinery for the camera path, direct-light connections, and the
// independent transparency estimate. Candidate medium events come from a
// majorant process; each walk decides how those candidates affect its estimator.
// Multiple importance sampling (MIS) combines radiance paths generated by
// BSDF/phase continuation with those generated by direct-light connections.
namespace {
// A reproducible unidirectional reference for diagnosing MIS independently of
// direct-light sampling. Set before loading the package in a fresh R process.
bool use_light_sampling() {
  static const bool enabled = !(std::getenv("RAYRENDER_VOLUME_REFERENCE") &&
                                std::string(std::getenv("RAYRENDER_VOLUME_REFERENCE")) == "true");
  return enabled;
}


// Keep throughput and sampling-density terms in double precision while long
// chains of null events multiply their weights. Convert radiance back to renderer
// Float at output; Average() combines the three RGB proposal channels.
struct RGB {
  double v[3];
  RGB(double x = 0) : v{x, x, x} {}
  RGB(const point3f &p) : v{p[0], p[1], p[2]} {}
  double &operator[](int i) { return v[i]; }
  double operator[](int i) const { return v[i]; }

  RGB operator+(const RGB &b) const {
    RGB r;
    for (int i = 0; i < 3; ++i)
      r[i] = v[i] + b[i];
    return r;
  }
  RGB operator*(const RGB &b) const {
    RGB r;
    for (int i = 0; i < 3; ++i)
      r[i] = v[i] * b[i];
    return r;
  }
  RGB operator/(double b) const {
    RGB r;
    for (int i = 0; i < 3; ++i)
      r[i] = v[i] / b;
    return r;
  }

  RGB &operator*=(const RGB &b) {
    for (int i = 0; i < 3; ++i)
      v[i] *= b[i];
    return *this;
  }
  RGB &operator+=(const RGB &b) {
    for (int i = 0; i < 3; ++i)
      v[i] += b[i];
    return *this;
  }
  RGB &operator/=(double b) {
    for (auto &x : v)
      x /= b;
    return *this;
  }
  double Average() const { return (v[0] + v[1] + v[2]) / 3; }
  double Max() const { return std::max({v[0], v[1], v[2]}); }
  point3f FloatRGB() const { return point3f(v[0], v[1], v[2]); }
};


// Beer-Lambert attenuation for constant coefficients. Handle a zero coefficient
// explicitly so an infinite distance does not produce the undefined product 0*inf.
RGB transmittance(const point3f &sigma, double distance) {
  RGB r;
  for (int i = 0; i < 3; ++i)
    r[i] = sigma[i] == 0 ? 1 : std::exp(-double(sigma[i]) * distance);
  return r;
}


bool cancelled(const std::atomic<bool> *c) { return c && c->load(std::memory_order_relaxed); }


// Throughput and the two MIS density terms appear as ratios in contributions.
// Scaling all three together preserves those ratios while avoiding numerical
// extremes during long sequences of null collisions.
void rescale(RGB &beta, RGB &ru, RGB &rl) {
  double scale = std::max({beta.Max(), ru.Max(), rl.Max()});
  if (scale > 1e80 || (scale > 0 && scale < 1e-80)) {
    beta /= scale;
    ru /= scale;
    rl /= scale;
  }
}


// Spend two sampler dimensions on a seed, then draw the variable number of
// tracking candidates from a local RNG. Candidate counts therefore do not consume
// the sampler dimensions reserved for subsequent scattering decisions.
random_gen tracking_rng(Sampler *sampler) {
  uint32_t a = uint32_t(double(sampler->Get1D()) * 4294967295.0);
  uint32_t b = uint32_t(double(sampler->Get1D()) * 4294967295.0);
  uint32_t seed = a ^ (b + 0x9e3779b9u + (a << 6) + (a >> 2));
  seed ^= seed >> 16;
  seed *= 0x7feb352du;
  seed ^= seed >> 15;
  seed *= 0x846ca68bu;
  seed ^= seed >> 16;
  return random_gen(seed);
}


// Overlapping dielectrics use the smallest priority value to select absorption.
// Participating-medium extinction is tracked separately from this glass segment.
RGB glass_transmittance(const VolumePathState &state, double distance) {
  const dielectric *active = nullptr;
  for (const auto *d : state.glass)
    if (!active || d->priority < active->priority)
      active = d;
  return active ? transmittance(active->attenuation, distance) : RGB(1);
}


// Region selection follows boundary membership, including zero-density cells
// and nested media. Glass always excludes the clear-air transport model.
bool integrate_atmosphere(const Atmosphere *atmosphere, const VolumePathState &state) {
  return atmosphere && state.glass.empty() &&
         (atmosphere->IntegrateInVolumes() || !state.Active());
}


// Dielectric membership depends on geometry, even when a shading normal differs.
// Older hit records can fall back to their only available normal.
normal3f geometric_normal(const hit_record &h) {
  return h.geometric_normal.squared_length() > 0 ? h.geometric_normal : h.normal;
}


// Offset the new origin to avoid hitting the same boundary again, and attach
// the current medium/glass membership to the ray used by intersection routines.
Ray spawn(const hit_record &h, const vec3f &wi, Float time, VolumePathState &state) {
  point3f o = OffsetMediumOrigin(h, wi);
  Ray r(o, wi, time);
  state.SetRay(r);
  return r;
}


// An ordinary surface may coincide with a medium boundary. Its normal offset
// can cross that boundary before the next intersection. Resolve only such nearby
// crossings; ordinary surface spawns retain the incremental path state.
void reconcile_surface_origin(const VolumeScene *scene, const hit_record &h, Ray &ray,
                              VolumePathState &state, const std::atomic<bool> *cancel) {
  if (!scene || !scene->boundary_bvh)
    return;
  Float tolerance = 8 * std::numeric_limits<Float>::epsilon() *
                        std::max({Float(1), std::abs(h.p[0]), std::abs(h.p[1]), std::abs(h.p[2])}) +
                    h.pError.length();
  vec3f offset = ray.o - h.p;
  vec3f direction = offset.squared_length() > 0 ? unit_vector(offset) : unit_vector(ray.d);


  // Probe only the error-sized neighbourhood of the surface. Rebuild containment
  // at the spawned origin only if an actual medium boundary is present there.
  Ray probe(h.p - direction * (2 * tolerance), direction, ray.time());
  probe.segment_absorption = true;
  hit_record contact;
  random_gen rng(0);
  if (scene->boundary_bvh->hit(probe, 0, 4 * tolerance, contact, rng)) {
    state = scene->InitialState(ray, cancel);
    state.SetRay(ray);
  }
}


// incoming points along propagation toward the surface, not away from it.
// Equal normal-dot-product signs therefore mean transmission across the boundary;
// reflection leaves medium membership unchanged.
void cross_if_transmitted(VolumePathState &state, const hit_record &h, const vec3f &incoming,
                          const vec3f &outgoing) {
  if (h.medium_boundary &&
      dot(incoming, h.geometric_normal) * dot(outgoing, h.geometric_normal) > 0)
    state.Cross(h, outgoing);
}


// Null collisions fill the gap between the majorant and physical extinction.
// A true bound violation invalidates tracking probabilities; only roundoff-sized
// negative gaps are tolerated and clamped away.
point3f null_coefficient(const MediumProperties &mp, const point3f &majorant) {
  point3f n;
  for (int i = 0; i < 3; ++i) {
    double st = double(mp.sigma_a[i]) + mp.sigma_s[i];
    if (!std::isfinite(st) || mp.sigma_a[i] < 0 || mp.sigma_s[i] < 0 ||
        st > double(majorant[i]) * (1 + 2e-5) + 1e-12)
      throw std::runtime_error("Medium coefficients exceed their majorant or are invalid.");
    n[i] = std::max(0.0, double(majorant[i]) - st);
  }
  return n;
}


// Callback receives world distance and the majorant transmittance since its last
// invocation. The returned value is the residual transmittance to the endpoint.
template <class Callback>
RGB sample_majorant(const MediumEntry &entry, const Ray &ray, double distance, int hero,
                    random_gen &rng, Callback &&callback, const std::atomic<bool> *cancel,
                    VolumeStatistics *stats = nullptr, bool scalar_majorant = false) {
  const Medium &medium = *entry.boundary->medium;

  // Do not normalize the transformed direction: retaining its scale keeps the
  // ray parameter in world-distance units, including for scaled medium instances.
  Transform inverse = Inverse(entry.medium_to_world);
  Ray local(inverse(ray.o), inverse(ray.d), ray.time());
  auto iterator = medium.SampleRay(local, distance);
  RGB T(1);


  // Walk intervals with constant majorants. Carry transmission across intervals
  // until a candidate is found, so callbacks see the full distance since the
  // previous candidate rather than just the most recent grid cell.
  while (auto seg = iterator.Next()) {
    if (stats)
      stats->segments.fetch_add(1, std::memory_order_relaxed);
    double t = seg->t_min;
    point3f majorant = seg->sigma_maj;
    // A shared RGB rate keeps the path-space ratios constant between candidate
    // events, so finite atmospheric source integrals can be accumulated there.
    if (scalar_majorant)
      majorant = point3f(std::max({majorant[0], majorant[1], majorant[2]}));
    double rate = majorant[hero];
    if (rate == 0) {
      T *= transmittance(majorant, seg->t_max - t);
      continue;
    }


    // Invert the exponential free-flight CDF. Clamp away from one and force
    // representable forward progress when a near-zero draw rounds back to t.
    while (t < seg->t_max && !cancelled(cancel)) {
      double u = std::clamp(double(rng.unif_rand()), 0.0, std::nextafter(1.0, 0.0));
      double candidate = t - std::log1p(-u) / rate;
      if (candidate <= t)
        candidate = std::nextafter(t, INFINITY);
      if (candidate >= seg->t_max) {
        T *= transmittance(majorant, seg->t_max - t);
        break;
      }

      // The caller classifies the event and owns any resulting termination or
      // scattering. Reset the interval transmission only after it was consumed.
      T *= transmittance(majorant, candidate - t);
      MediumProperties mp = medium.SamplePoint(local(Float(candidate)));
      if (!callback(candidate, mp, majorant, T))
        return RGB(1);
      T = RGB(1);
      t = candidate;
    }
    if (cancelled(cancel))
      return RGB(1);
  }
  return T;
}


// Background opacity needs extinction along the original camera direction,
// independently of the radiance path's scattering events. Homogeneous media
// have an analytic answer; heterogeneous media use RGB ratio tracking below.
RGB segment_opacity_transmittance(const MediumEntry &entry, const Ray &ray, double distance,
                                  random_gen &rng, const std::atomic<bool> *cancel) {
  const Medium &medium = *entry.boundary->medium;
  if (medium.IsHomogeneous())
    return transmittance(medium.sigma_a + medium.sigma_s, distance);


  // One shared majorant rate bounds all channels. At each candidate, multiply
  // by the channel's probability of a null event to estimate its transmission.
  Transform inverse = Inverse(entry.medium_to_world);
  Ray local(inverse(ray.o), inverse(ray.d), ray.time());
  auto iterator = medium.SampleRay(local, distance);
  RGB tr(1);
  while (auto seg = iterator.Next()) {
    double rate = std::max({seg->sigma_maj[0], seg->sigma_maj[1], seg->sigma_maj[2]});
    if (rate == 0)
      continue;
    double t = seg->t_min;
    while (!cancelled(cancel)) {
      double next =
          t - std::log1p(-std::min(double(rng.unif_rand()), std::nextafter(1.0, 0.0))) / rate;
      t = next <= t ? std::nextafter(t, INFINITY) : next;
      if (t >= seg->t_max)
        break;
      auto mp = medium.SamplePoint(local(Float(t)));
      null_coefficient(mp, seg->sigma_maj);
      for (int i = 0; i < 3; ++i)
        tr[i] *= std::max(0.0, 1 - (double(mp.sigma_a[i]) + mp.sigma_s[i]) / rate);
      if (tr.Max() == 0)
        return tr;
    }
    if (cancelled(cancel))
      break;
  }
  return tr;
}


// Follow a separate straight camera ray for alpha. Boundary-only surfaces and
// masked/invisible hits let it continue; a visible finite surface blocks the
// background, while reaching the environment returns the remaining transmission.
Float primary_transparency(const Ray &input, VolumePathState state, hitable *world, random_gen &rng,
                           const std::atomic<bool> *cancel, const Atmosphere *atmosphere) {
  Ray ray(input.o, unit_vector(input.d), input.time());
  state.SetRay(ray);
  RGB tr(1);
  const bool outside_only = atmosphere && !atmosphere->IntegrateInVolumes();
  bool air_active = integrate_atmosphere(atmosphere, state);
  point3f air_origin = ray.o;
  while (!cancelled(cancel)) {
    hit_record h;
    if (!world->hit(ray, 0, MaxT, h, rng))
      return Float(tr.Average());
    double distance = h.t;

    // The default needs one infinite query. Outside-only haze instead multiplies
    // each completed air interval and the final tail; volume interiors are never
    // included in a transmission query. Ordinary alpha masks do not split fits.
    if (atmosphere && h.infinite_area_hit && (!outside_only || air_active))
      tr *= RGB(atmosphere->Transmission(outside_only ? air_origin : input.o, ray.d, INFINITY));
    tr *= glass_transmittance(state, distance);
    if (const auto *entry = state.Active())
      tr *= segment_opacity_transmittance(*entry, ray, distance, rng, cancel);


    if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
      bool next_air = integrate_atmosphere(atmosphere, state);
      if (outside_only && air_active && !next_air) {
        double d = dot(ray(Float(distance)) - air_origin, ray.d);
        tr *= RGB(atmosphere->Transmission(air_origin, ray.d, std::max(0.0, d)));
      }
      ray = spawn(h, ray.d, ray.time(), state);
      if (outside_only && !air_active && next_air) air_origin = ray.o;
      air_active = next_air;
      continue;
    }


    bool invisible = false;
    // Infinite endpoints are always visible. Evaluating their spectral radiance
    // here would duplicate the radiance walk just to obtain a visibility flag.
    if (h.mat_ptr && !h.infinite_area_hit)
      h.mat_ptr->emitted(ray, h, h.u, h.v, h.p, invisible);
    if (h.alpha_miss || invisible) {
      ray = spawn(h, ray.d, ray.time(), state);
      continue;
    }
    return h.infinite_area_hit ? Float(tr.Average()) : 0;
  }
  return 0;
}


// Both direct-light connections and emitter hits must query the same directional
// light distribution. Prefer the volume scene's sampler, with the legacy fallback.
Float light_pdf(hitable_list *lights, const point3f &p, const vec3f &wi, random_gen &rng,
                Float time) {
  if (lights->volume_scene && lights->volume_scene->light_sampler)
    return lights->volume_scene->light_sampler->Pdf(p, wi, rng, time);
  return lights->size() ? lights->pdf_value(p, wi, rng, time) : 0;
}


// A connection first chooses a direction and PDF, then records the emitter
// actually reached by the shadow walk along that direction.
struct LightSample {
  vec3f wi;
  hit_record endpoint;
  point3f radiance{0};
  double distance = 0;
  Float pdf = 0;
  const hitable *emitter = nullptr;
};


// Estimate direct illumination at a surface or medium collision. Trace the chosen
// direction through null events and boundary transitions, carrying the density
// terms needed to compare light sampling with the BSDF/phase-function strategy.
RGB direct_light(const Ray &parent, const point3f &p, const hit_record *surface, pdf *bsdf_pdf,
                 const HGPhaseFunction *phase, VolumePathState state, const RGB &beta,
                 const RGB &rp, hitable *world, hitable_list *lights, int hero, random_gen &rng,
                 Sampler *sampler, const std::atomic<bool> *cancel) {
  if (!lights->size() || !use_light_sampling())
    return RGB(0);
  VolumeStatistics *stats = lights->volume_scene && lights->volume_scene->collect_statistics
                                ? &lights->volume_scene->statistics
                                : nullptr;


  // Select a light direction, then evaluate the full light-mixture PDF there.
  // Invalid or zero-density proposals cannot form a contribution.
  LightSample sample;
  sample.wi = lights->volume_scene && lights->volume_scene->light_sampler
                  ? lights->volume_scene->light_sampler->Sample(p, sampler, parent.time())
                  : lights->random(p, sampler, parent.time());
  if (!(sample.wi.squared_length() > 0))
    return RGB(0);
  sample.wi = unit_vector(sample.wi);
  sample.pdf = light_pdf(lights, p, sample.wi, rng, parent.time());
  if (!(sample.pdf > 0) || !std::isfinite(sample.pdf))
    return RGB(0);


  // Evaluate scattering and the competing directional PDF at this same direction.
  // state is a copy, so a transmitted connection can cross the surface without
  // changing the camera path's medium membership.
  RGB f;
  Float ps;
  if (surface) {
    f = RGB(surface->mat_ptr->f(parent, *surface, sample.wi));
    ps = bsdf_pdf->value(sample.wi, rng, parent.time());
    cross_if_transmitted(state, *surface, parent.d, sample.wi);
  } else {
    ps = phase->p(-parent.d, sample.wi);
    f = RGB(ps);
  }
  if (!(f.Max() > 0))
    return RGB(0);


  // A surface connection needs a geometric origin offset; a medium collision
  // starts directly at its interaction point. Reconcile coincident boundaries.
  Ray ray =
      surface ? spawn(*surface, sample.wi, parent.time(), state) : Ray(p, sample.wi, parent.time());
  state.SetRay(ray);
  if (surface)
    reconcile_surface_origin(lights->volume_scene.get(), *surface, ray, state, cancel);


  // tr tracks connection throughput; ru and rl track the relative density terms
  // for unidirectional and light-sampled paths. rp carries the camera-path prefix.
  // Atmospheric source radiance accumulates along the connection as well.
  RGB tr(1), ru(1), rl(1);
  RGB atmospheric_light(0);
  const point3f lighting_origin = ray.o;
  const Atmosphere *atmosphere = lights->volume_scene ? lights->volume_scene->atmosphere : nullptr;
  random_gen tracker = tracking_rng(sampler);
  AtmosphereRay atmosphere_ray(atmosphere);
  const bool deferred_haze = atmosphere && atmosphere->DeferredHaze();
  random_gen haze_rng = deferred_haze ? tracking_rng(sampler) : random_gen(0);
  auto flush_haze = [&]() {
    if (!deferred_haze) return;
    double endpoint_uniform = 0, correction_uniform = 0;
    if (atmosphere->SampleHazeCorrection()) {
      endpoint_uniform = haze_rng.unif_rand();
      correction_uniform = haze_rng.unif_rand();
    }
    auto segment = atmosphere_ray.Flush(endpoint_uniform, correction_uniform);
    for (int c = 0; c < 3; ++c) atmospheric_light[c] += segment.radiance[c];
    tr *= RGB(segment.transmission);
  };
  while (!cancelled(cancel)) {
    const bool integrate_haze = integrate_atmosphere(atmosphere, state);
    atmosphere_ray.Start(ray.o, ray.d, integrate_haze);
    hit_record h;
    if (!world->hit(ray, 0, MaxT, h, rng)) {
      flush_haze();
      return atmospheric_light;
    }
    double distance = h.t, previous_distance = 0;


    // Add clear-air in-scattering before attenuating the remaining connection.
    // A fixed atmosphere anchor survives null events and ordinary boundaries.
    // Excluded regions pause it; glass absorption still uses each local segment.
    auto advance = [&](double end) {
      double d = end - previous_distance;
      if (integrate_haze && d > 0) {
        double denom = (rl * rp * RGB(sample.pdf) + ru * rp * RGB(ps)).Average();
        if (deferred_haze) {
          RGB weight = denom > 0 ? beta * f * tr / denom : RGB(0);
          atmosphere_ray.Accumulate(ray(Float(end)), {weight[0], weight[1], weight[2]}, haze_rng.unif_rand());
        } else {
          auto segment = atmosphere_ray.Advance(ray(Float(end)));
          if (denom > 0)
            atmospheric_light += beta * f * tr * RGB(segment.radiance) / denom;
          tr *= RGB(segment.transmission);
        }
      }
      tr *= glass_transmittance(state, d);
      previous_distance = end;
    };


    // A shadow connection keeps its direction. Ratio tracking treats candidates
    // as null events, reducing throughput by extinction instead of choosing a
    // real scattering direction as the main path would.
    if (const auto *entry = state.Active()) {
      RGB T = sample_majorant(
          *entry, ray, distance, hero, tracker,
          [&](double t, const MediumProperties &mp, const point3f &m, const RGB &T) {
            advance(t);
            if (stats)
              stats->shadow_candidates.fetch_add(1, std::memory_order_relaxed);
            double pdf = T[hero] * m[hero];
            if (!(pdf > 0)) {
              tr = RGB(0);
              return false;
            }
            RGB n(null_coefficient(mp, m));

            // The unidirectional density includes null-collision probabilities;
            // the light strategy uses the majorant candidate density instead.
            tr *= T * n / pdf;
            ru *= T * n / pdf;
            rl *= T * RGB(m) / pdf;
            rescale(tr, ru, rl);

            // Stop weak connections stochastically, doubling the surviving
            // throughput to compensate for the one-half survival probability.
            // Deferred haze uses the current weight before pending extinction.
            // This may trace longer connections; roulette remains compensated
            // without querying the atmosphere at every candidate just to stop.
            double relative = (ru + rl).Average();
            if (relative > 0 && tr.Max() / relative < .05) {
              if (tracker.unif_rand() < .5) {
                tr = RGB(0);
                return false;
              }
              tr *= RGB(2);
            }
            return tr.Max() > 0;
          },
          cancel, stats, atmosphere && atmosphere->IntegrateInVolumes());
      if (tr.Max() == 0) {
        flush_haze();
        return atmospheric_light;
      }

      // No further candidate occurred before the endpoint. Correct every RGB
      // channel for that residual interval relative to the chosen hero channel.
      if (T[hero] > 0) {
        RGB w = T / T[hero];
        tr *= w;
        ru *= w;
        rl *= w;
      }
    }


    // The environment is mathematically at infinity. Subtract already counted
    // haze from the radiance at the fixed atmospheric ray origin.
    if (!h.infinite_area_hit) advance(distance);
    else tr *= glass_transmittance(state, distance - previous_distance);


    // Boundary-only geometry and alpha-mask misses do not terminate the light
    // connection. Boundary crossings update membership before continuing straight.
    if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
      // Keep collecting across a boundary if haze stays enabled on both sides.
      // Excluded regions must resolve the preceding air span before pausing it.
      if (integrate_haze != integrate_atmosphere(atmosphere, state)) flush_haze();
      ray = spawn(h, ray.d, ray.time(), state);
      continue;
    }
    if (h.alpha_miss) {
      ray = spawn(h, ray.d, ray.time(), state);
      continue;
    }
    flush_haze();
    bool invisible = false;
    Ray emission_ray = ray;


    // Query infinite emission at the original lighting vertex, or the finite
    // atmosphere's anchor, so invisible boundaries cannot change its altitude.
    // A nonemissive finite endpoint still retains haze accumulated before it.
    if (h.infinite_area_hit) {
      emission_ray = Ray(atmosphere ? atmosphere_ray.Origin(ray.o) : lighting_origin, ray.d, ray.time());
      state.SetRay(emission_ray);
    }
    sample.radiance = h.mat_ptr ? h.mat_ptr->emitted(emission_ray, h, h.u, h.v, h.p, invisible) : point3f(0);
    if (atmosphere && h.infinite_area_hit)
      sample.radiance = atmosphere_ray.Remaining(sample.radiance);
    sample.endpoint = h;
    sample.distance = (h.p - p).length();
    sample.emitter = h.shape;


    // Balance the light and BSDF/phase strategies after including their medium
    // density terms, and combine endpoint emission with the connection's haze.
    double denominator = (rl * rp * RGB(sample.pdf) + ru * rp * RGB(ps)).Average();
    if (denominator > 0)
      atmospheric_light += beta * f * tr * RGB(sample.radiance) / denominator;
    return atmospheric_light;
  }
  return RGB(0);
}
} // namespace


// Main radiance walk: alternate between medium candidates and surface vertices.
// Absorption stops the path, real scattering creates a new direction, and null
// events or invisible boundaries only update transport along the current ray.
void color_volume(const Ray &input, hitable *world, hitable_list *lights, size_t max_depth,
                  size_t roulette_depth, random_gen &rng, Sampler *sampler, Float &transparency,
                  point3f &radiance, normal3f &normal, point3f &albedo,
                  const std::atomic<bool> *cancel) {
  // Initialize image outputs and the medium/glass membership at the camera.
  radiance = point3f(0);
  normal = normal3f(0);
  albedo = point3f(0);
  transparency = 0;
  const VolumeScene *scene = lights->volume_scene.get();
  VolumeStatistics *stats = scene && scene->collect_statistics ? &scene->statistics : nullptr;
  if (stats)
    stats->paths.fetch_add(1, std::memory_order_relaxed);
  VolumePathState state = scene ? scene->InitialState(input, cancel) : VolumePathState{};
  if (!scene && input.pri_stack)
    state.glass = *input.pri_stack;


  // One uniformly selected RGB channel proposes free flights and event types.
  // All three channels remain in the estimator through their relative weights.
  // Alpha gets its own straight-ray estimate and tracking stream.
  int hero = std::min(2, int(sampler->Get1D() * 3));
  if (scene && scene->has_media) {
    auto alpha_rng = tracking_rng(sampler);
    transparency = primary_transparency(input, state, world, alpha_rng, cancel, scene->atmosphere);
  }


  // L accumulates contributions and beta carries throughput. ru and rl are the
  // rescaled unidirectional/light-sampling density terms used in MIS denominators.
  // Keep the previous scattering vertex for evaluating competing light proposals.
  Ray ray(input.o, unit_vector(input.d), input.time());
  state.SetRay(ray);
  RGB L(0), beta(1), ru(1), rl(1);
  double eta_scale = 1;
  point3f previous_point(0);
  // Native lighting without finite haze still belongs to the last real vertex.
  // Crossing an invisible cloud boundary must not move its altitude query.
  point3f lighting_origin = ray.o;
  bool specular = true, any_diffuse = false, wrote_feature = false;
  size_t depth = 0;
  const Atmosphere *atmosphere = scene ? scene->atmosphere : nullptr;
  AtmosphereRay atmosphere_ray(atmosphere);
  const bool deferred_haze = atmosphere && atmosphere->DeferredHaze();
  random_gen haze_rng = deferred_haze ? tracking_rng(sampler) : random_gen(0);
  auto flush_haze = [&]() {
    if (!deferred_haze) return;
    double endpoint_uniform = 0, correction_uniform = 0;
    if (atmosphere->SampleHazeCorrection()) {
      endpoint_uniform = haze_rng.unif_rand();
      correction_uniform = haze_rng.unif_rand();
    }
    auto segment = atmosphere_ray.Flush(endpoint_uniform, correction_uniform);
    for (int c = 0; c < 3; ++c) L[c] += segment.radiance[c];
    beta *= RGB(segment.transmission);
  };


  while (!cancelled(cancel)) {
    // Find the next geometric endpoint while retaining the atmosphere anchor
    // across straight-through events. A new direction or excluded region resets it.
    const bool integrate_haze = integrate_atmosphere(atmosphere, state);
    atmosphere_ray.Start(ray.o, ray.d, integrate_haze);
    hit_record h;
    if (!world->hit(ray, 0, MaxT, h, rng)) {
      flush_haze();
      break;
    }
    double distance = h.t, previous_distance = 0;
    Float atmosphere_light_pdf = integrate_haze && !specular && use_light_sampling()
                                     ? light_pdf(lights, previous_point, ray.d, rng, ray.time()) : 0;


    // Between candidates, add clear-air source radiance with the current MIS
    // weights before applying attenuation. Glass absorption advances over the
    // same distance, while clear-air transport follows the selected air regions.
    auto advance = [&](double end) {
      double d = end - previous_distance;
      if (integrate_haze && d > 0) {
        double denom = (ru + rl * RGB(atmosphere_light_pdf)).Average();
        if (deferred_haze) {
          RGB weight = denom > 0 ? beta / denom : RGB(0);
          atmosphere_ray.Accumulate(ray(Float(end)), {weight[0], weight[1], weight[2]}, haze_rng.unif_rand());
        } else {
          auto segment = atmosphere_ray.Advance(ray(Float(end)));
          if (denom > 0) L += beta * RGB(segment.radiance) / denom;
          beta *= RGB(segment.transmission);
        }
      }
      beta *= glass_transmittance(state, d);
      previous_distance = end;
    };


    // Process the active medium up to the geometric hit. The callback may leave
    // the direction unchanged, terminate this path, or replace it after scattering.
    bool scattered = false, terminated = false;
    if (const auto *entry = state.Active()) {
      auto tracker = tracking_rng(sampler);
      RGB T = sample_majorant(
          *entry, ray, distance, hero, tracker,
          [&](double t, const MediumProperties &mp, const point3f &m, const RGB &T) {
            advance(t);
            point3f n = null_coefficient(mp, m);
            double proposal = T[hero] * m[hero];
            if (!(proposal > 0)) {
              terminated = true;
              return false;
            }


            // Estimate local medium emission at every candidate before classifying
            // it. Correct the absorption-weighted source for the candidate proposal
            // and RGB density term, independent of the subsequent event choice.
            if (depth < max_depth) {
              // An emitting candidate needs extinction at its own position.
              // Nonemissive null events can keep accumulating cheap weights.
              if ((RGB(mp.sigma_a) * RGB(mp.Le)).Max() > 0) flush_haze();
              RGB re = ru * T * RGB(m) / proposal;
              if (re.Average() > 0)
                L += beta * T * RGB(mp.sigma_a) * RGB(mp.Le) / proposal / re.Average();
            }


            // Thin the hero-channel majorant into absorption, scattering, or the
            // remaining null probability. Absorption ends further transport.
            double mode = tracker.unif_rand(), pa = mp.sigma_a[hero] / m[hero],
                   ps = mp.sigma_s[hero] / m[hero];
            if (mode < pa) {
              terminated = true;
              return false;
            }


            // A real scattering event consumes a bounce and reweights the RGB
            // channels by their scattering coefficients relative to the proposal.
            if (mode < pa + ps) {
              flush_haze();
              if (depth >= max_depth) {
                terminated = true;
                return false;
              }
              ++depth;
              if (stats)
                stats->scattering_events.fetch_add(1, std::memory_order_relaxed);
              double pdf = T[hero] * mp.sigma_s[hero];
              if (!(pdf > 0)) {
                terminated = true;
                return false;
              }
              RGB w = T * RGB(mp.sigma_s) / pdf;
              beta *= w;
              ru *= w;


              // Reconstructed surface positions can lie off the ray by their
              // error bound. Keep a near-endpoint collision on the segment's
              // interior side when converting its double distance to a Float point.
              double tolerance =
                  8 * std::numeric_limits<Float>::epsilon() *
                      std::max({1.0, std::abs(double(ray.o[0])), std::abs(double(ray.o[1])),
                                std::abs(double(ray.o[2])), distance}) +
                  h.pError.length();
              double position_t = distance - t < tolerance ? std::max(0.0, t - tolerance) : t;
              point3f collision;
              for (int a = 0; a < 3; ++a)
                collision[a] = Float(double(ray.o[a]) + double(ray.d[a]) * position_t);
              MediumInteraction interaction{collision, -ray.d, ray.time(), mp};
              point3f p = interaction.p;


              // Connect this vertex to a sampled light, then continue using a
              // phase-function sample. Store its density for MIS at the next
              // emission or atmospheric contribution along the continued path.
              L += direct_light(ray, p, nullptr, nullptr, &interaction.properties.phase, state,
                                beta, ru, world, lights, hero, rng, sampler, cancel);
              vec2f u = sampler->Get2D();
              auto sample = mp.phase.Sample(-ray.d, u.xy.x, u.xy.y);
              beta *= RGB(sample.p / sample.pdf);
              rl = ru / sample.pdf;
              previous_point = p;
              ray = Ray(p, unit_vector(sample.wi), ray.time());
              lighting_origin = p;
              state.SetRay(ray);
              scattered = true;
              specular = false;
              any_diffuse = true;

              // A first volume interaction has no surface normal/albedo guide.
              // Mark the feature as written so a later surface cannot replace it.
              if (!wrote_feature) {
                normal = normal3f(0);
                albedo = point3f(0);
                wrote_feature = true;
              }
              return false;
            }


            // A null event preserves direction and bounce depth. Its probability
            // still changes throughput and the two competing path-density terms.
            if (stats)
              stats->null_events.fetch_add(1, std::memory_order_relaxed);
            double pdf = T[hero] * n[hero];
            if (!(pdf > 0)) {
              terminated = true;
              return false;
            }
            RGB w = T * RGB(n) / pdf;
            beta *= w;
            ru *= w;
            rl *= T * RGB(m) / pdf;
            rescale(beta, ru, rl);
            if (!(beta.Max() > 0) || !(ru.Max() > 0)) {
              terminated = true;
              return false;
            }
            return true;
          },
          cancel, stats, atmosphere && atmosphere->IntegrateInVolumes());


      // A callback that scattered already installed the new ray. Apply roulette
      // there and start another iteration; only an unscattered path reaches the
      // original geometric endpoint and needs the residual interval correction.
      if (terminated) {
        flush_haze();
        break;
      }
      if (scattered) {
        if (depth > roulette_depth) {
          double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
          if (!(survival > 0) || sampler->Get1D() >= survival)
            break;
          beta /= survival;
        }
        continue;
      }
      if (T[hero] > 0) {
        RGB w = T / T[hero];
        beta *= w;
        ru *= w;
        rl *= w;
      }
    }


    // Complete local transport to a finite hit. The environment's geometric
    // shell is only a tracing endpoint; its atmospheric tail is handled through
    // the infinite radiance query below, not a finite haze segment to that shell.
    if (!h.infinite_area_hit) advance(distance);
    else beta *= glass_transmittance(state, distance - previous_distance);


    // Invisible medium boundaries and alpha-mask misses continue the same path
    // without spending a bounce or changing the last real scattering proposal.
    if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
      if (integrate_haze != integrate_atmosphere(atmosphere, state)) flush_haze();
      ray = spawn(h, ray.d, ray.time(), state);
      continue;
    }
    if (h.alpha_miss) {
      ray = spawn(h, ray.d, ray.time(), state);
      continue;
    }
    flush_haze();
    bool invisible = false;
    Ray emission_ray = ray;


    // Evaluate infinite emission at the last real lighting vertex or atmospheric
    // anchor. Hidden emitters can be skipped before diffuse/medium scattering.
    if (h.infinite_area_hit) {
      emission_ray = Ray(atmosphere ? atmosphere_ray.Origin(ray.o) : lighting_origin, ray.d, ray.time());
      state.SetRay(emission_ray);
    }
    point3f le = h.mat_ptr ? h.mat_ptr->emitted(emission_ray, h, h.u, h.v, h.p, invisible) : point3f(0);
    if (invisible && !any_diffuse) {
      ray = spawn(h, ray.d, ray.time(), state);
      continue;
    }


    // A transparent camera background hides distant emission while retaining
    // clear-air haze. Remove haze already integrated along the path before adding
    // the remaining environment contribution with its emission-hit MIS weight.
    if (depth == 0 && h.infinite_area_hit && !(scene && scene->has_media))
      transparency = 1;
    bool hide_background =
        scene && scene->transparent_background && depth == 0 && h.infinite_area_hit;
    if (hide_background && atmosphere)
      le = atmosphere->SkyRadiance(emission_ray.o, emission_ray.d);
    if (atmosphere && h.infinite_area_hit)
      le = atmosphere_ray.Remaining(le);
    if (!hide_background || atmosphere) {
      double denom = ru.Average();
      if (!specular && use_light_sampling())
        denom =
            (ru + rl * RGB(light_pdf(lights, previous_point, ray.d, rng, ray.time()))).Average();
      if (denom > 0)
        L += beta * RGB(le) / denom;
    }


    // Emission is allowed at the terminal vertex before enforcing the depth
    // limit. Further surface scattering requires positive throughput and density.
    if (depth >= max_depth || !(beta.Max() > 0) || !(ru.Average() > 0) || !h.mat_ptr)
      break;
    scatter_record s;
    // Dielectric membership uses the oriented geometric normal, not a shading normal.
    hit_record shading_hit = h;
    if (h.mat_ptr->is_dielectric())
      shading_hit.normal = geometric_normal(h);
    if (!h.mat_ptr->scatter(ray, shading_hit, s, sampler))
      break;


    // Record the first interaction's denoising features. Passthrough materials
    // may continue a ray without consuming a scattering depth.
    if (!wrote_feature) {
      normal = h.normal;
      albedo = h.mat_ptr->get_albedo(h);
      wrote_feature = true;
    }
    if (!s.is_passthrough)
      ++depth;


    // Delta reflection/refraction supplies its own direction. Account for the
    // radiance-mode eta^2 factor on transmission and keep a compensating factor
    // for roulette, so temporary changes inside glass do not kill paths too early.
    if (s.is_specular) {
      beta *= RGB(s.attenuation);
      if (s.is_transmission && !s.is_passthrough) {
        double eta2 = double(s.eta) * s.eta;
        beta /= eta2;
        eta_scale *= eta2;
      }
      cross_if_transmitted(state, h, ray.d, s.specular_ray.d);
      ray = spawn(h, unit_vector(s.specular_ray.d), ray.time(), state);
      if (!s.is_passthrough)
        specular = true;
    } else {
      // Nondelta surfaces use both light sampling and BSDF continuation. Keep
      // the continuation PDF for the competing strategy at the next vertex.
      L += direct_light(ray, h.p, &h, s.pdf_ptr, nullptr, state, beta, ru, world, lights, hero, rng,
                        sampler, cancel);
      vec3f wi = s.pdf_ptr->generate(sampler, any_diffuse, ray.time());
      if (!(wi.squared_length() > 0))
        break;
      wi = unit_vector(wi);
      Float p = s.pdf_ptr->value(wi, rng, ray.time());
      if (!(p > 0) || !std::isfinite(p))
        break;
      beta *= RGB(h.mat_ptr->f(ray, h, wi)) / p;
      rl = ru / p;
      previous_point = h.p;
      specular = false;
      any_diffuse = true;
      cross_if_transmitted(state, h, ray.d, wi);
      ray = spawn(h, wi, ray.time(), state);
    }


    // Repair membership if the surface offset crossed a coincident boundary,
    // stabilize the RGB ratios, and apply compensated roulette after real bounces.
    reconcile_surface_origin(scene, h, ray, state, cancel);
    if (!s.is_passthrough)
      lighting_origin = ray.o;
    rescale(beta, ru, rl);
    if (!s.is_passthrough && depth > roulette_depth) {
      double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
      if (!(survival > 0) || sampler->Get1D() >= survival)
        break;
      beta /= survival;
    }
  }


  // Perform the final precision conversion only after all contributions are summed.
  radiance = L.FloatRGB();
}
