// RGB adaptation of PBRT v4's null-scattering path-space MIS estimator.
// https://pbr-book.org/4ed/Light_Transport_II_Volume_Rendering/Volume_Scattering_Integrators
#include "volpath.h"
#include "boundary.h"
#include "haze.h"
#include "subsurface.h"
#include "../materials/openpbr.h"
#include <algorithm>
#include <limits>
#include <stdexcept>


// Shared machinery for the camera path, direct-light connections, and the
// independent transparency estimate. Candidate medium events come from a
// majorant process; each walk decides how those candidates affect its estimator.
// Multiple importance sampling (MIS) combines radiance paths generated by
// BSDF/phase continuation with those generated by direct-light connections.
namespace {
// A reproducible unidirectional reference for diagnosing MIS independently of
// direct-light sampling. Set before loading the package in a fresh R process.
bool use_light_sampling() {
  static const bool enabled = !(std::getenv("RAYRENDER_VOLUME_REFERENCE") &&
                                std::string(std::getenv("RAYRENDER_VOLUME_REFERENCE")) == "true");
  return enabled;
}


// Keep throughput and sampling-density terms in double precision while long
// chains of null events multiply their weights. Convert radiance back to renderer
// Float at output; Average() combines the three RGB proposal channels.
struct RGB {
  double v[3];
  RGB(double x = 0) : v{x, x, x} {}
  RGB(const point3f &p) : v{p[0], p[1], p[2]} {}
  double &operator[](int i) { return v[i]; }
  double operator[](int i) const { return v[i]; }

  RGB operator+(const RGB &b) const {
    RGB r;
    for (int i = 0; i < 3; ++i)
      r[i] = v[i] + b[i];
    return r;
  }
  RGB operator*(const RGB &b) const {
    RGB r;
    for (int i = 0; i < 3; ++i)
      r[i] = v[i] * b[i];
    return r;
  }
  RGB operator/(double b) const {
    RGB r;
    for (int i = 0; i < 3; ++i)
      r[i] = v[i] / b;
    return r;
  }

  RGB &operator*=(const RGB &b) {
    for (int i = 0; i < 3; ++i)
      v[i] *= b[i];
    return *this;
  }
  RGB &operator+=(const RGB &b) {
    // Validate the whole contribution before changing any accumulated channel.
    // A failed sample retains all radiance accumulated before this addition.
    for (int i = 0; i < 3; ++i)
      if (!std::isfinite(v[i] + b[i]) || !std::isfinite(Float(v[i] + b[i])))
        throw PathFailure(PathFailureKind::Radiance,
                          "Radiance exceeds the output buffer range. Check scene units, illumination, and coefficients.");
    for (int i = 0; i < 3; ++i) v[i] += b[i];
    return *this;
  }
  RGB &operator/=(double b) {
    for (auto &x : v)
      x /= b;
    return *this;
  }
  double Average() const { return (v[0] + v[1] + v[2]) / 3; }
  double Max() const { return std::max({v[0], v[1], v[2]}); }
  point3f FloatRGB() const { return point3f(v[0], v[1], v[2]); }
};


// Beer-Lambert attenuation for constant coefficients. Handle a zero coefficient
// explicitly so an infinite distance does not produce the undefined product 0*inf.
RGB transmittance(const point3f &sigma, double distance) {
  RGB r;
  for (int i = 0; i < 3; ++i)
    r[i] = sigma[i] == 0 ? 1 : std::exp(-double(sigma[i]) * distance);
  return r;
}


bool cancelled(const std::atomic<bool> *c) { return c && c->load(std::memory_order_relaxed); }


// Throughput and the two MIS density terms appear as ratios in contributions.
// Scaling all three together preserves those ratios while avoiding numerical
// extremes during long sequences of null collisions.
void rescale(RGB &beta, RGB &ru, RGB &rl) {
  double scale = std::max({beta.Max(), ru.Max(), rl.Max()});
  if (scale > 1e80 || (scale > 0 && scale < 1e-80)) {
    beta /= scale;
    ru /= scale;
    rl /= scale;
  }
}

// An analytic homogeneous segment has no augmented null events. Apply physical,
// continuation, and light densities separately. The selected hero density is a
// common divisor and cancels; normalize all terms together in log space instead.
// This also handles optical thickness large enough to underflow exp(-sigma*t).
void subsurface_segment(RGB &beta, RGB &ru, RGB &rl, const Medium &medium,
                        const SubsurfaceProposal &proposal, const vec3f &wi,
                        double distance, bool collision) {
  if (medium.subsurface_accelerated && collision && !proposal.guided) {
    // For an ordinary collision the physical and proposal factors share T:
    // beta *= T*sigma_s, ru *= T*sigma_t, rl = 0. Most sampled optical depths
    // are small, so taking logs of every incoming weight and exponentiating
    // them again is unnecessary. Normalize by the same common maximum used
    // below. Keep log space for guided mixtures and ill-conditioned values.
    // With tau <= 32 and positive weights/coefficients in [1e-80, 1e80],
    // these products cannot overflow/underflow before normalization. 
    double extinction[3];
    bool ordinary_range = std::isfinite(distance) && distance >= 0;
    for (int c = 0; c < 3; ++c) {
      extinction[c] = double(medium.sigma_a[c]) + medium.sigma_s[c];
      ordinary_range &= extinction[c] * distance <= 32 &&
                        extinction[c] == proposal.extinction[c];
      for (double value : {beta[c], ru[c]})
        ordinary_range &= value == 0 || (value >= 1e-80 && value <= 1e80);
      for (double coefficient : {extinction[c], double(medium.sigma_s[c])})
        ordinary_range &= coefficient == 0 || (coefficient >= 1e-80 && coefficient <= 1e80);
    }
    if (ordinary_range) {
      double largest = 0;
      for (int c = 0; c < 3; ++c) {
        double transmission = std::exp(-extinction[c] * distance);
        beta[c] *= transmission * medium.sigma_s[c];
        ru[c] *= transmission * extinction[c];
        largest = std::max({largest, beta[c], ru[c]});
      }
      rl = RGB(0);
      if (largest > 0) { beta /= largest; ru /= largest; }
      return;
    }
  }
  double logs[3][3], largest = -INFINITY;
  RGB *values[3] = {&beta, &ru, &rl};
  for (int c = 0; c < 3; ++c) {
    double st = double(medium.sigma_a[c]) + medium.sigma_s[c];
    double physical = st == 0 ? 0 : -st * distance;
    // Cast before log: the Float overload otherwise rounds a coefficient's log
    // before it enters this double-precision likelihood calculation.
    if (collision) physical += medium.sigma_s[c] > 0 ? std::log(double(medium.sigma_s[c])) : -INFINITY;
    double factors[3] = {physical, proposal.LogDistancePdf(c, wi, distance, collision),
                         collision ? -INFINITY : 0};
    for (int j = 0; j < 3; ++j) {
      logs[j][c] = (*values[j])[c] > 0 ? std::log((*values[j])[c]) + factors[j] : -INFINITY;
      if (std::isnan(logs[j][c]) || logs[j][c] == INFINITY)
        throw PathFailure(PathFailureKind::Density, "Non-finite subsurface density. Check coefficients and scene scale.");
      largest = std::max(largest, logs[j][c]);
    }
  }
  for (int j = 0; j < 3; ++j)
    for (int c = 0; c < 3; ++c)
      (*values[j])[c] = largest == -INFINITY ? 0 : std::exp(logs[j][c] - largest);
}

const Medium *subsurface_medium(const hit_record &h) {
  const Medium *m = h.medium_boundary ? h.medium_boundary->medium.get() : nullptr;
  return m && m->subsurface ? m : nullptr;
}

void cross_subsurface(VolumePathState &state, const hit_record &h, const vec3f &wi) {
  state.CrossDielectric(h, wi);
}

bool priority_hidden(const VolumePathState &state, const hit_record &h, const vec3f &wi) {
  return h.mat_ptr && h.mat_ptr->is_dielectric() &&
         (subsurface_medium(h) || state.ContainsSubsurface()) && state.Interface(h, wi).Hidden();
}

// A smooth, ordinary dielectric has no directional scattering when the active
// IORs match exactly. Cross it as a null interface on BOTH camera and light
// paths: preserve the previous vertex/PDF, but still change the absorbing region.
// Deliberately exclude derived/layered materials and SSS surface models; equal
// IOR alone does not remove their other scattering lobes. No IOR tolerance is
// used, since even a small real mismatch can produce grazing-angle reflection.
bool cross_matched_dielectric(VolumePathState &state, const hit_record &h,
                              const vec3f &direction, RGB &weight,
                              const VolumePathState *adjacent = nullptr) {
  if (!h.mat_ptr || typeid(*h.mat_ptr) != typeid(dielectric) || h.alpha_miss ||
      (h.medium_boundary && (!h.medium_boundary->keep_surface || subsurface_medium(h))))
    return false;
  auto interface = state.Interface(h, direction);
  if (adjacent) interface.after = adjacent->ActiveDielectric();
  if (interface.Eta() != 1) return false;

  // Match ordinary camera transport: surface tint is applied once on entry,
  // never on a priority-hidden boundary. Beer-Lambert absorption belongs to the
  // following segment and is already handled by glass_transmittance().
  if (!interface.Hidden() && interface.entering)
    weight *= RGB(static_cast<const dielectric *>(h.mat_ptr)->albedo);
  if (adjacent) state = *adjacent;
  else state.CrossDielectric(h, direction);
  return true;
}


// Spend two sampler dimensions on a seed, then draw the variable number of
// tracking candidates from a local RNG. Candidate counts therefore do not consume
// the sampler dimensions reserved for subsequent scattering decisions.
random_gen tracking_rng(Sampler *sampler) {
  uint32_t a = uint32_t(double(sampler->Get1D()) * 4294967295.0);
  uint32_t b = uint32_t(double(sampler->Get1D()) * 4294967295.0);
  uint32_t seed = a ^ (b + 0x9e3779b9u + (a << 6) + (a >> 2));
  seed ^= seed >> 16;
  seed *= 0x7feb352du;
  seed ^= seed >> 15;
  seed *= 0x846ca68bu;
  seed ^= seed >> 16;
  return random_gen(seed);
}


// Overlapping dielectrics use the smallest priority value to select absorption.
// Participating-medium extinction is tracked separately from this glass segment.
RGB glass_transmittance(const VolumePathState &state, double distance) {
  const dielectric *active = state.ActiveDielectric();
  return active ? transmittance(active->attenuation, distance) : RGB(1);
}


// Decide whether this medium can contain any haze. The medium switch, glass,
// and global switch take precedence over the optional density cutoff.
bool integrate_atmosphere(const Atmosphere *atmosphere, const VolumePathState &state) {
  const auto *entry = state.Active();
  return atmosphere && state.glass.empty() &&
         (!entry || (atmosphere->IntegrateInVolumes() && entry->boundary->medium->haze));
}


MediumHazeIterator haze_intervals(const Atmosphere *atmosphere, const VolumePathState &state,
                                  const Ray &ray, double end, const std::atomic<bool> *cancel) {
  bool enabled = integrate_atmosphere(atmosphere, state);
  const auto *entry = enabled ? state.Active() : nullptr;
  if (!entry || entry->boundary->medium->haze_density_threshold == 0)
    return MediumHazeIterator(nullptr, ray, end, enabled, cancel);
  Transform inverse = Inverse(entry->medium_to_world);
  return MediumHazeIterator(entry->boundary->medium.get(),
                             Ray(inverse(ray.o), inverse(ray.d), ray.time()), end, enabled, cancel);
}


// Consume selection intervals only as far as the next scattering candidate or
// endpoint. Classification is spatial and never depends on random event spacing.
// Callers flush pending haze before a selection change resets the model anchor.
class HazeIntervalWalk {
public:
  explicit HazeIntervalWalk(MediumHazeIterator intervals) : intervals(std::move(intervals)) {
    current = this->intervals.Next(false);
  }
  bool Initial() const { return current && current->integrate; }
  template<class Select, class Advance>
  void To(double end, Select &&select, Advance &&advance) {
    while (current && position < end) {
      bool enabled = current->integrate;
      select(enabled, position);
      // Merge only up to the requested event. Voxel/majorant knots by themselves
      // neither query Prague nor reset its cumulative ray anchor.
      do {
        position = std::min(end, current->t_max);
        if (position >= current->t_max) current = intervals.Next(false);
      } while (current && position < end && current->integrate == enabled);
      if (enabled) advance(position);
    }
  }
private:
  MediumHazeIterator intervals;
  std::optional<MediumHazeSegment> current;
  double position = 0;
};


// Dielectric membership depends on geometry, even when a shading normal differs.
// Older hit records can fall back to their only available normal.
normal3f geometric_normal(const hit_record &h) {
  return h.geometric_normal.squared_length() > 0 ? h.geometric_normal : h.normal;
}


// Offset the new origin to avoid hitting the same boundary again, and attach
// the current medium/glass membership to the ray used by intersection routines.
Ray spawn(const hit_record &h, const vec3f &wi, Float time, VolumePathState &state) {
  point3f o = OffsetMediumOrigin(h, wi);
  Ray r(o, wi, time);
  state.SetRay(r);
  return r;
}


// An ordinary surface may coincide with a medium boundary. Its normal offset
// can cross that boundary before the next intersection. Resolve only such nearby
// crossings; ordinary surface spawns retain the incremental path state.
void reconcile_surface_origin(const VolumeScene *scene, const hit_record &h, Ray &ray,
                              VolumePathState &state, const std::atomic<bool> *cancel) {
  if (!scene || !scene->boundary_bvh)
    return;
  Float tolerance = 8 * std::numeric_limits<Float>::epsilon() *
                        std::max({Float(1), std::abs(h.p[0]), std::abs(h.p[1]), std::abs(h.p[2])}) +
                    h.pError.length();
  // Probe only the error-sized neighbourhood of the surface. Rebuild containment
  // at the spawned origin only if an actual medium boundary is present there.
  // A surface's offset may run parallel to a nearby medium boundary (a vertical
  // cookie wall meeting a horizontal milk cap). Checking only that direction
  // misses contact even when rounding puts the new origin on the wrong side.
  // Three orthogonal probes cover local planar contacts without changing the
  // actual ray origin, geometry, or strict crossing checks away from contact.
  hit_record contact;
  random_gen rng(0);
  bool nearby = false;
  for (int axis = 0; axis < 3 && !nearby; ++axis) {
    vec3f direction(0);
    direction[axis] = 1;
    Ray probe(h.p - direction * (2 * tolerance), direction, ray.time());
    probe.segment_absorption = true;
    nearby = scene->boundary_bvh->hit(probe, 0, 4 * tolerance, contact, rng);
  }
  if (nearby) {
    auto previous = state.Active() ? std::optional<MediumEntry>(*state.Active()) : std::nullopt;
    state = scene->InitialState(ray, cancel);
    if (previous && state.Active() && previous->boundary_id == state.Active()->boundary_id) {
      state.Active()->guide_axis = previous->guide_axis;
      state.Active()->guide_valid = previous->guide_valid;
    }
    state.SetRay(ray);
  }
}


// incoming points along propagation toward the surface, not away from it.
// Equal normal-dot-product signs therefore mean transmission across the boundary;
// reflection leaves medium membership unchanged.
void cross_if_transmitted(VolumePathState &state, const hit_record &h, const vec3f &incoming,
                          const vec3f &outgoing) {
  if (h.medium_boundary &&
      dot(incoming, h.geometric_normal) * dot(outgoing, h.geometric_normal) > 0)
    state.Cross(h, outgoing);
}


// Null collisions fill the gap between the majorant and physical extinction.
// A true bound violation invalidates tracking probabilities; only roundoff-sized
// negative gaps are tolerated and clamped away.
point3f null_coefficient(const MediumProperties &mp, const point3f &majorant) {
  point3f n;
  for (int i = 0; i < 3; ++i) {
    double st = double(mp.sigma_a[i]) + mp.sigma_s[i];
    if (!std::isfinite(st) || mp.sigma_a[i] < 0 || mp.sigma_s[i] < 0 ||
        st > double(majorant[i]) * (1 + 2e-5) + 1e-12)
      throw PathFailure(PathFailureKind::Majorant, "Medium coefficients exceed their majorant or are invalid.");
    n[i] = std::max(0.0, double(majorant[i]) - st);
  }
  return n;
}


// Callback receives world distance and the majorant transmittance since its last
// invocation. The returned value is the residual transmittance to the endpoint.
template <class Callback>
RGB sample_majorant(const MediumEntry &entry, const Ray &ray, double distance, int hero,
                    random_gen &rng, Callback &&callback, const std::atomic<bool> *cancel,
                    VolumeStatistics *stats = nullptr, bool scalar_majorant = false) {
  const Medium &medium = *entry.boundary->medium;

  // Do not normalize the transformed direction: retaining its scale keeps the
  // ray parameter in world-distance units, including for scaled medium instances.
  Transform inverse = Inverse(entry.medium_to_world);
  Ray local(inverse(ray.o), inverse(ray.d), ray.time());
  auto iterator = medium.SampleRay(local, distance);
  RGB T(1);


  // Walk intervals with constant majorants. Carry transmission across intervals
  // until a candidate is found, so callbacks see the full distance since the
  // previous candidate rather than just the most recent grid cell.
  while (auto seg = iterator.Next()) {
    if (stats)
      stats->segments.fetch_add(1, std::memory_order_relaxed);
    double t = seg->t_min;
    point3f majorant = seg->sigma_maj;
    // A shared RGB rate keeps the path-space ratios constant between candidate
    // events, so finite atmospheric source integrals can be accumulated there.
    if (scalar_majorant)
      majorant = point3f(std::max({majorant[0], majorant[1], majorant[2]}));
    double rate = majorant[hero];
    if (rate == 0) {
      T *= transmittance(majorant, seg->t_max - t);
      continue;
    }


    // Invert the exponential free-flight CDF. Clamp away from one and force
    // representable forward progress when a near-zero draw rounds back to t.
    while (t < seg->t_max && !cancelled(cancel)) {
      double u = std::clamp(double(rng.unif_rand()), 0.0, std::nextafter(1.0, 0.0));
      double candidate = t - std::log1p(-u) / rate;
      if (candidate <= t)
        candidate = std::nextafter(t, INFINITY);
      if (candidate >= seg->t_max) {
        T *= transmittance(majorant, seg->t_max - t);
        break;
      }

      // The caller classifies the event and owns any resulting termination or
      // scattering. Reset the interval transmission only after it was consumed.
      T *= transmittance(majorant, candidate - t);
      MediumProperties mp = medium.SamplePoint(local(Float(candidate)));
      if (!callback(candidate, mp, majorant, T))
        return RGB(1);
      T = RGB(1);
      t = candidate;
    }
    if (cancelled(cancel))
      return RGB(1);
  }
  return T;
}


// Background opacity needs extinction along the original camera direction,
// independently of the radiance path's scattering events. Homogeneous media
// have an analytic answer; heterogeneous media use RGB ratio tracking below.
RGB segment_opacity_transmittance(const MediumEntry &entry, const Ray &ray, double distance,
                                  random_gen &rng, const std::atomic<bool> *cancel) {
  if (entry.boundary->medium->subsurface_diffusion) return RGB(0);
  const Medium &medium = *entry.boundary->medium;
  if (medium.IsHomogeneous())
    return transmittance(medium.sigma_a + medium.sigma_s, distance);


  // One shared majorant rate bounds all channels. At each candidate, multiply
  // by the channel's probability of a null event to estimate its transmission.
  Transform inverse = Inverse(entry.medium_to_world);
  Ray local(inverse(ray.o), inverse(ray.d), ray.time());
  auto iterator = medium.SampleRay(local, distance);
  RGB tr(1);
  while (auto seg = iterator.Next()) {
    double rate = std::max({seg->sigma_maj[0], seg->sigma_maj[1], seg->sigma_maj[2]});
    if (rate == 0)
      continue;
    double t = seg->t_min;
    while (!cancelled(cancel)) {
      double next =
          t - std::log1p(-std::min(double(rng.unif_rand()), std::nextafter(1.0, 0.0))) / rate;
      t = next <= t ? std::nextafter(t, INFINITY) : next;
      if (t >= seg->t_max)
        break;
      auto mp = medium.SamplePoint(local(Float(t)));
      null_coefficient(mp, seg->sigma_maj);
      for (int i = 0; i < 3; ++i)
        tr[i] *= std::max(0.0, 1 - (double(mp.sigma_a[i]) + mp.sigma_s[i]) / rate);
      if (tr.Max() == 0)
        return tr;
    }
    if (cancelled(cancel))
      break;
  }
  return tr;
}


// Follow a separate straight camera ray for alpha. Boundary-only surfaces and
// masked/invisible hits let it continue; a visible finite surface blocks the
// background, while reaching the environment returns the remaining transmission.
Float primary_transparency(const Ray &input, VolumePathState state, hitable *world, random_gen &rng,
                           const std::atomic<bool> *cancel, const Atmosphere *atmosphere) {
  Ray ray(input.o, unit_vector(input.d), input.time());
  state.SetRay(ray);
  RGB tr(1);
  bool air_active = false;
  point3f air_origin = ray.o;
  while (!cancelled(cancel)) {
    hit_record h;
    if (!world->hit(ray, 0, MaxT, h, rng))
      return Float(tr.Average());
    double distance = h.t;

    // Close transmission intervals only at actual selection changes. In
    // threshold mode this includes density crossings inside one boundary, while
    // keeping one common fit across adjacent cells and ordinary volume entries.
    auto intervals = haze_intervals(atmosphere, state, ray, distance, cancel);
    while (auto interval = intervals.Next()) {
      point3f p = ray(Float(interval->t_min));
      if (air_active && !interval->integrate) {
        double d = dot(p - air_origin, ray.d);
        if (d > 0) tr *= RGB(atmosphere->Transmission(air_origin, ray.d, d));
      }
      if (!air_active && interval->integrate) air_origin = p;
      air_active = interval->integrate;
    }
    if (atmosphere && h.infinite_area_hit && air_active)
      tr *= RGB(atmosphere->Transmission(air_origin, ray.d, INFINITY));
    tr *= glass_transmittance(state, distance);
    if (const auto *entry = state.Active())
      tr *= segment_opacity_transmittance(*entry, ray, distance, rng, cancel);


    if (priority_hidden(state, h, ray.d)) {
      state.CrossDielectric(h, ray.d);
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }


    bool invisible = false;
    // Infinite endpoints are always visible. Evaluating their spectral radiance
    // here would duplicate the radiance walk just to obtain a visibility flag.
    if (h.mat_ptr && !h.infinite_area_hit)
      h.mat_ptr->emitted(ray, h, h.u, h.v, h.p, invisible);
    if (h.alpha_miss || invisible) {
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    return h.infinite_area_hit ? Float(tr.Average()) : 0;
  }
  return 0;
}


// Atmospheric source terms use the marginal directional light distribution.
// Ordinary emitter hits instead use the selected-emitter density below.
Float light_pdf(hitable_list *lights, const point3f &p, const vec3f &wi, random_gen &rng,
                Float time) {
  if (lights->volume_scene && lights->volume_scene->light_sampler)
    return lights->volume_scene->light_sampler->Pdf(p, wi, rng, time);
  return lights->size() ? lights->pdf_value(p, wi, rng, time) : 0;
}


// Transport data shared by the atmospheric and selected-emitter strategies.
struct LightSample {
  vec3f wi;
  hit_record endpoint;
  point3f radiance{0};
  double distance = 0;
  Float pdf = 0;
  const hitable *emitter = nullptr;
};


// Estimate direct illumination at a surface or medium collision. Trace the chosen
// direction through null events and boundary transitions, carrying the density
// terms needed to compare light sampling with the BSDF/phase-function strategy.
RGB direct_area_light(const Ray &parent, const point3f &p, const hit_record *surface, pdf *bsdf_pdf,
                 const HGPhaseFunction *phase, VolumePathState state, const RGB &beta,
                 const RGB &rp, hitable *world, hitable_list *lights, int hero, random_gen &rng,
                 Sampler *sampler, const std::atomic<bool> *cancel,
                 const SubsurfaceProposal *sss_proposal = nullptr,
                 const SubsurfaceBoundaryBSDF *sss_bsdf = nullptr,
                 const DiffusionExitBSDF *diffusion_exit = nullptr,
                 const OpenPBRInteraction *openpbr = nullptr) {
  if (!lights->size() || !use_light_sampling())
    return RGB(0);
  VolumeStatistics *stats = lights->volume_scene && lights->volume_scene->collect_statistics
                                ? &lights->volume_scene->statistics
                                : nullptr;


  // With atmospheric transport, the marginal direction distribution also
  // samples haze before a blocker. Otherwise select an explicit emitter and
  // use its joint selection/direction density on both sides of MIS.
  const auto *scene = lights->volume_scene.get();
  const VolumeLightSampler *emitter_sampler = scene && !scene->atmosphere
      ? scene->light_sampler.get() : nullptr;
  VolumeLightSampler::Selection selected;
  LightSample sample;
  if (emitter_sampler) {
    VolumeLightSampler::Context context{p, surface ?
        (diffusion_exit ? diffusion_exit->Normal() : sss_bsdf ? geometric_normal(*surface) :
         (surface->has_bump ? surface->bump_normal : surface->normal)) : normal3f(0), parent.time()};
    selected = emitter_sampler->SampleEmitter(context, sampler, rng);
    sample.wi = selected.wi;
    sample.pdf = selected.pdf;
  } else {
    sample.wi = scene && scene->light_sampler
        ? scene->light_sampler->Sample(p, sampler, parent.time())
        : lights->random(p, sampler, parent.time());
    if (!(sample.wi.squared_length() > 0)) return RGB(0);
    sample.wi = unit_vector(sample.wi);
    sample.pdf = light_pdf(lights, p, sample.wi, rng, parent.time());
  }
  if (!(sample.pdf > 0) || !std::isfinite(sample.pdf)) return RGB(0);


  // Evaluate scattering and the competing directional PDF at this same direction.
  // state is a copy, so a transmitted connection can cross the surface without
  // changing the camera path's medium membership.
  RGB f;
  RGB ps;
  if (openpbr) {
    f = RGB(openpbr->Evaluate(sample.wi));
    ps = RGB(openpbr->Pdf(sample.wi));
    if (surface->mat_ptr->is_dielectric() &&
        dot(parent.d, surface->geometric_normal) * dot(sample.wi, surface->geometric_normal) > 0)
      state.CrossDielectric(*surface, sample.wi);
  } else if (diffusion_exit) {
    // The sampled diffusion endpoint already supplies its exterior membership.
    f = RGB(diffusion_exit->Evaluate(sample.wi));
    ps = RGB(diffusion_exit->Pdf(sample.wi));
  } else if (sss_bsdf) {
    f = RGB(sss_bsdf->Evaluate(sample.wi));
    ps = RGB(sss_bsdf->Pdf(sample.wi));
    if (dot(parent.d, surface->geometric_normal) * dot(sample.wi, surface->geometric_normal) > 0)
      cross_subsurface(state, *surface, sample.wi);
  } else if (surface) {
    f = RGB(surface->mat_ptr->f(parent, *surface, sample.wi));
    ps = RGB(bsdf_pdf->value(sample.wi, rng, parent.time()));
    cross_if_transmitted(state, *surface, parent.d, sample.wi);
  } else {
    f = RGB(phase->p(-parent.d, sample.wi));
    ps = f;
    if (sss_proposal)
      for (int c = 0; c < 3; ++c) ps[c] = sss_proposal->DirectionPdf(c, sample.wi);
  }
  if (!(f.Max() > 0))
    return RGB(0);


  // A surface connection needs a geometric origin offset; a medium collision
  // starts directly at its interaction point. Reconcile coincident boundaries.
  Ray ray =
      surface ? spawn(*surface, sample.wi, parent.time(), state) : Ray(p, sample.wi, parent.time());
  state.SetRay(ray);
  if (surface)
    reconcile_surface_origin(lights->volume_scene.get(), *surface, ray, state, cancel);


  // tr tracks connection throughput; ru and rl track the relative density terms
  // for unidirectional and light-sampled paths. rp carries the camera-path prefix.
  // Atmospheric source radiance accumulates along the connection as well.
  RGB tr(1), ru(1), rl(1);
  RGB atmospheric_light(0);
  const point3f lighting_origin = ray.o;
  const Atmosphere *atmosphere = lights->volume_scene ? lights->volume_scene->atmosphere : nullptr;
  random_gen tracker = tracking_rng(sampler);

  // Resolve only the selected emitter, then ask whether anything blocks the
  // finite connection. Other lamps are blockers too. Keep the existing ordered
  // walk for media, alpha masks and materials with stochastic intersections.
  if (emitter_sampler && state.media.empty() && state.glass.empty() &&
      world->ShadowType() != OpaqueShadowType::Unsupported) {
    hit_record endpoint;
    if (!emitter_sampler->Endpoint(selected, ray, endpoint, rng)) return RGB(0);
    if (std::isfinite(endpoint.t) && endpoint.t > 0) {
      const Float margin = 64 * std::numeric_limits<Float>::epsilon() *
                           std::max(Float(1), std::abs(endpoint.t));
      const Float before = std::max(Float(0), endpoint.t - margin);
      if (before > 0 && world->OpaqueHit(ray, 0, before, rng)) return RGB(0);
      // Resolve the tiny endpoint interval in closest-hit order. This preserves
      // coincident-surface ordering without treating the light itself as a blocker.
      hit_record endpoint_hit;
      if (!world->hit(ray, before, endpoint.t + margin, endpoint_hit, rng) ||
          !emitter_sampler->Matches(selected, endpoint_hit)) return RGB(0);
      bool invisible = false;
      Ray emission_ray = ray;
      if (endpoint_hit.infinite_area_hit) {
        emission_ray = Ray(lighting_origin, ray.d, ray.time());
        state.SetRay(emission_ray);
      }
      point3f emitted = endpoint_hit.mat_ptr
          ? endpoint_hit.mat_ptr->emitted(emission_ray, endpoint_hit, endpoint_hit.u,
                                         endpoint_hit.v, endpoint_hit.p, invisible)
          : point3f(0);
      double denominator = (rp * RGB(sample.pdf) + rp * RGB(ps)).Average();
      return denominator > 0 ? beta * f * RGB(emitted) / denominator : RGB(0);
    }
  }
  AtmosphereRay atmosphere_ray(atmosphere);
  bool air_active = false;
  const bool deferred_haze = atmosphere && atmosphere->DeferredHaze();
  const bool sample_haze = atmosphere && atmosphere->SampleHaze();
  random_gen haze_rng = (deferred_haze || sample_haze) ? tracking_rng(sampler) : random_gen(0);
  auto flush_haze = [&]() {
    if (!deferred_haze) return;
    double endpoint_uniform = -1, correction_uniform = -1;
    if (sample_haze) {
      endpoint_uniform = haze_rng.unif_rand();
      correction_uniform = haze_rng.unif_rand();
    }
    auto segment = atmosphere_ray.Flush(endpoint_uniform, correction_uniform);
    for (int c = 0; c < 3; ++c) atmospheric_light[c] += segment.radiance[c];
    tr *= RGB(segment.transmission);
  };
  auto select_haze = [&](bool enabled, const point3f &p) {
    if (air_active && !enabled) flush_haze();
    atmosphere_ray.Start(p, ray.d, enabled);
    air_active = enabled;
  };
  while (!cancelled(cancel)) {
    const bool integrate_haze = integrate_atmosphere(atmosphere, state);
    hit_record h;
    if (!world->hit(ray, 0, MaxT, h, rng)) {
      flush_haze();
      return atmospheric_light;
    }
    double distance = h.t, previous_distance = 0;
    HazeIntervalWalk haze_walk(haze_intervals(atmosphere, state, ray, distance, cancel));
    select_haze(haze_walk.Initial(), ray.o);


    // Add clear-air in-scattering before attenuating the remaining connection.
    // A fixed atmosphere anchor survives null events and ordinary boundaries.
    // Excluded regions pause it; glass absorption still uses each local segment.
    auto advance = [&](double end) {
      double d = end - previous_distance;
      haze_walk.To(end, [&](bool enabled, double start) {
        select_haze(enabled, ray(Float(start)));
      }, [&](double stop) {
        double denom = (rl * rp * RGB(sample.pdf) + ru * rp * RGB(ps)).Average();
        if (deferred_haze) {
          RGB weight = denom > 0 ? beta * f * tr / denom : RGB(0);
          atmosphere_ray.Accumulate(ray(Float(stop)), {weight[0], weight[1], weight[2]}, haze_rng.unif_rand());
        } else {
          auto segment = atmosphere_ray.Advance(ray(Float(stop)), sample_haze ? haze_rng.unif_rand() : -1);
          if (denom > 0)
            atmospheric_light += beta * f * tr * RGB(segment.radiance) / denom;
          tr *= RGB(segment.transmission);
        }
      });
      tr *= glass_transmittance(state, d);
      previous_distance = end;
    };


    // A shadow connection keeps its direction. Ratio tracking treats candidates
    // as null events, reducing throughput by extinction instead of choosing a
    // real scattering direction as the main path would.
    if (const auto *entry = state.Active()) {
      const Medium &medium = *entry->boundary->medium;
      if (medium.subsurface_diffusion) {
        flush_haze();
        return atmospheric_light; // diffusion has no straight ballistic component
      }
      if (medium.subsurface) {
        auto ordinary = SubsurfaceProposal::Ordinary(medium);
        subsurface_segment(tr, ru, rl, medium, sss_proposal ? *sss_proposal : ordinary,
                            ray.d, distance, false);
      } else {
      RGB T = sample_majorant(
          *entry, ray, distance, hero, tracker,
          [&](double t, const MediumProperties &mp, const point3f &m, const RGB &T) {
            advance(t);
            if (stats)
              stats->shadow_candidates.fetch_add(1, std::memory_order_relaxed);
            double pdf = T[hero] * m[hero];
            if (!(pdf > 0)) {
              tr = RGB(0);
              return false;
            }
            RGB n(null_coefficient(mp, m));

            // The unidirectional density includes null-collision probabilities;
            // the light strategy uses the majorant candidate density instead.
            tr *= T * n / pdf;
            ru *= T * n / pdf;
            rl *= T * RGB(m) / pdf;
            rescale(tr, ru, rl);

            // Stop weak connections stochastically, doubling the surviving
            // throughput to compensate for the one-half survival probability.
            // Deferred haze uses the current weight before pending extinction.
            // This may trace longer connections; roulette remains compensated
            // without querying the atmosphere at every candidate just to stop.
            double relative = (ru + rl).Average();
            if (relative > 0 && tr.Max() / relative < .05) {
              if (tracker.unif_rand() < .5) {
                tr = RGB(0);
                return false;
              }
              tr *= RGB(2);
            }
            return tr.Max() > 0;
          },
          cancel, stats, integrate_haze);
      if (tr.Max() == 0) {
        flush_haze();
        return atmospheric_light;
      }

      // No further candidate occurred before the endpoint. Correct every RGB
      // channel for that residual interval relative to the chosen hero channel.
      if (T[hero] > 0) {
        RGB w = T / T[hero];
        tr *= w;
        ru *= w;
        rl *= w;
      }
      }
    }


    sss_proposal = nullptr;
    // The environment is mathematically at infinity. Subtract already counted
    // haze from the radiance at the fixed atmospheric ray origin.
    if (!h.infinite_area_hit) advance(distance);
    else tr *= glass_transmittance(state, distance - previous_distance);


    // Boundary-only geometry and alpha-mask misses do not terminate the light
    // connection. Boundary crossings update membership before continuing straight.
    if (priority_hidden(state, h, ray.d)) {
      state.CrossDielectric(h, ray.d);
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
      // The next segment resolves pending haze before any selection change.
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    if (h.alpha_miss) {
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    if (cross_matched_dielectric(state, h, ray.d, tr)) {
      Ray next = spawn(h, ray.d, ray.time(), state);
      PropagateRayDifferentials(ray, h, next, false, 1, true);
      ray = next;
      continue;
    }
    flush_haze();
    bool invisible = false;
    Ray emission_ray = ray;


    // Query infinite emission at the original lighting vertex, or the finite
    // atmosphere's anchor, so invisible boundaries cannot change its altitude.
    // A nonemissive finite endpoint still retains haze accumulated before it.
    if (h.infinite_area_hit) {
      emission_ray = Ray(atmosphere ? atmosphere_ray.Origin(ray.o) : lighting_origin, ray.d, ray.time());
      state.SetRay(emission_ray);
    }
    if (emitter_sampler && !emitter_sampler->Matches(selected, h)) return RGB(0);
    sample.radiance = h.mat_ptr ? h.mat_ptr->emitted(emission_ray, h, h.u, h.v, h.p, invisible) : point3f(0);
    if (atmosphere && h.infinite_area_hit)
      sample.radiance = atmosphere_ray.Remaining(sample.radiance);
    sample.endpoint = h;
    sample.distance = (h.p - p).length();
    sample.emitter = h.shape;


    // Balance the light and BSDF/phase strategies after including their medium
    // density terms, and combine endpoint emission with the connection's haze.
    double denominator = (rl * rp * RGB(sample.pdf) + ru * rp * RGB(ps)).Average();
    if (denominator > 0)
      atmospheric_light += beta * f * tr * RGB(sample.radiance) / denominator;
    return atmospheric_light;
  }
  return RGB(0);
}
// Delta-position lights cannot be reached by a continuously sampled BSDF/phase
// direction. Their discrete selection PMF therefore has no competing MIS term.
// Estimate RGB shadow transmission independently of the camera path's spectral
// proposal; only the camera prefix rp belongs in the contribution denominator.
RGB direct_point_light(const Ray &parent, const point3f &p, const hit_record *surface,
                       const HGPhaseFunction *phase, VolumePathState state,
                       const RGB &beta, const RGB &rp, hitable *world,
                       const VolumeScene *scene, random_gen &rng, Sampler *sampler,
                       const std::atomic<bool> *cancel,
                       const SubsurfaceBoundaryBSDF *sss_bsdf,
                       const DiffusionExitBSDF *diffusion_exit,
                       const OpenPBRInteraction *openpbr) {
  if (!scene || scene->point_lights.Empty() || !use_light_sampling()) return RGB(0);
  const auto sample = scene->point_lights.Sample(p, sampler->Get1D());
  if (!(sample.pmf > 0) || !(RGB(sample.radiance).Max() > 0)) return RGB(0);
  RGB f;
  if (openpbr) {
    f = RGB(openpbr->Evaluate(sample.wi));
    if (surface->mat_ptr->is_dielectric() &&
        dot(parent.d, surface->geometric_normal) * dot(sample.wi, surface->geometric_normal) > 0)
      state.CrossDielectric(*surface, sample.wi);
  } else if (diffusion_exit) {
    f = RGB(diffusion_exit->Evaluate(sample.wi));
  } else if (sss_bsdf) {
    f = RGB(sss_bsdf->Evaluate(sample.wi));
    if (dot(parent.d, surface->geometric_normal) * dot(sample.wi, surface->geometric_normal) > 0)
      cross_subsurface(state, *surface, sample.wi);
  } else if (surface) {
    f = RGB(surface->mat_ptr->f(parent, *surface, sample.wi));
    cross_if_transmitted(state, *surface, parent.d, sample.wi);
  } else {
    f = RGB(phase->p(-parent.d, sample.wi));
  }
  if (!(f.Max() > 0)) return RGB(0);
  Ray ray = surface ? spawn(*surface, sample.wi, parent.time(), state)
                    : Ray(p, sample.wi, parent.time());
  state.SetRay(ray);
  if (surface) reconcile_surface_origin(scene, *surface, ray, state, cancel);
  RGB tr(1);
  random_gen tracker = tracking_rng(sampler);
  while (!cancelled(cancel)) {
    const double remaining = dot(sample.position - ray.o, ray.d);
    if (!(remaining > 0)) break;
    hit_record h;
    const bool found = world->hit(ray, 0, Float(remaining), h, rng) && !h.infinite_area_hit;
    const double distance = found ? h.t : remaining;
    tr *= glass_transmittance(state, distance);
    if (const auto *entry = state.Active())
      tr *= segment_opacity_transmittance(*entry, ray, distance, tracker, cancel);
    auto intervals = haze_intervals(scene->atmosphere, state, ray, distance, cancel);
    while (auto interval = intervals.Next())
      if (interval->integrate)
        tr *= RGB(scene->atmosphere->Transmission(ray(Float(interval->t_min)), ray.d,
                                                  interval->t_max - interval->t_min));
    if (!(tr.Max() > 0)) return RGB(0);
    if (!found) break;
    if (priority_hidden(state, h, ray.d)) {
      state.CrossDielectric(h, ray.d);
    } else if (cross_matched_dielectric(state, h, ray.d, tr)) {
      // The following segment uses the new priority-selected absorption.
    } else if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
    } else {
      bool invisible = false;
      if (h.mat_ptr) h.mat_ptr->emitted(ray, h, h.u, h.v, h.p, invisible);
      if (!h.alpha_miss && !invisible) return RGB(0);
    }
    { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
  }
  const double denominator = rp.Average() * sample.pmf;
  return !cancelled(cancel) && denominator > 0
      ? beta * f * tr * RGB(sample.radiance) / denominator : RGB(0);
}

RGB direct_light(const Ray &parent, const point3f &p, const hit_record *surface, pdf *bsdf_pdf,
                 const HGPhaseFunction *phase, VolumePathState state, const RGB &beta,
                 const RGB &rp, hitable *world, hitable_list *lights, int hero, random_gen &rng,
                 Sampler *sampler, const std::atomic<bool> *cancel,
                 const SubsurfaceProposal *sss_proposal = nullptr,
                 const SubsurfaceBoundaryBSDF *sss_bsdf = nullptr,
                 const DiffusionExitBSDF *diffusion_exit = nullptr,
                 const OpenPBRInteraction *openpbr = nullptr) {
  if (!lights->volume_scene || lights->volume_scene->point_lights.Empty())
    return direct_area_light(parent, p, surface, bsdf_pdf, phase, std::move(state), beta, rp,
        world, lights, hero, rng, sampler, cancel, sss_proposal, sss_bsdf, diffusion_exit, openpbr);
  RGB result = direct_area_light(parent, p, surface, bsdf_pdf, phase, state, beta, rp,
      world, lights, hero, rng, sampler, cancel, sss_proposal, sss_bsdf, diffusion_exit, openpbr);
  result += direct_point_light(parent, p, surface, phase, std::move(state), beta, rp, world,
      lights->volume_scene.get(), rng, sampler, cancel, sss_bsdf, diffusion_exit, openpbr);
  return result;
}
} // namespace


// Main radiance walk: alternate between medium candidates and surface vertices.
// Absorption stops the path, real scattering creates a new direction, and null
// events or invisible boundaries only update transport along the current ray.
void color_volume(const Ray &input, hitable *world, hitable_list *lights, size_t max_depth,
                  size_t roulette_depth, random_gen &rng, Sampler *sampler, Float &transparency,
                  point3f &radiance, normal3f &normal, point3f &albedo,
                  const std::atomic<bool> *cancel) {
  // Initialize image outputs and the medium/glass membership at the camera.
  radiance = point3f(0);
  normal = normal3f(0);
  albedo = point3f(0);
  transparency = 0;
  const VolumeScene *scene = lights->volume_scene.get();
  VolumeStatistics *stats = scene && scene->collect_statistics ? &scene->statistics : nullptr;
  if (stats)
    stats->paths.fetch_add(1, std::memory_order_relaxed);
  RGB L(0);
  Ray ray(input.o, unit_vector(input.d), input.time());
  VolumePathState state;
  size_t depth = 0;
  uint64_t internal_events = 0;
  const char *stage = "initial_membership";
  try {
  state = scene ? scene->InitialState(input, cancel) : VolumePathState{};
  if (!scene && input.pri_stack)
    state.glass = *input.pri_stack;


  // One uniformly selected RGB channel proposes free flights and event types.
  // All three channels remain in the estimator through their relative weights.
  // Alpha gets its own straight-ray estimate and tracking stream.
  int hero = std::min(2, int(sampler->Get1D() * 3));
  if (scene && scene->has_media) {
    auto alpha_rng = tracking_rng(sampler);
    // Reserve the same sampler dimensions for reproducible RGB paths, but do
    // not trace coverage that opaque output will discard. Transparent output
    // still uses the independent physical transmittance estimate unchanged.
    if (scene->transparent_background) {
      stage = "transparency";
      transparency = primary_transparency(input, state, world, alpha_rng, cancel, scene->atmosphere);
    }
  }


  // L accumulates contributions and beta carries throughput. ru and rl are the
  // rescaled unidirectional/light-sampling density terms used in MIS denominators.
  // Keep the previous scattering vertex for evaluating competing light proposals.
  stage = "radiance";
  state.SetRay(ray);
  RGB beta(1), ru(1), rl(1);
  double eta_scale = 1;
  VolumeLightSampler::Context previous_light_context;
  // Native lighting without finite haze still belongs to the last real vertex.
  // Crossing an invisible cloud boundary must not move its altitude query.
  point3f lighting_origin = ray.o;
  bool specular = true, any_diffuse = false, wrote_feature = false;
  std::optional<SubsurfaceProposal> subsurface_flight;
  std::optional<hit_record> diffusion_entry;
  uint64_t flight_boundary = 0;
  auto internal_roulette = [&]() {
    if (internal_events <= 5) return true;
    double density = ru.Average();
    double weight = density > 0 ? (beta * RGB(eta_scale) / density).Max() : 0;
    if (!std::isfinite(weight))
      throw PathFailure(PathFailureKind::Roulette, "Non-finite subsurface roulette weight. Check scene scale and coefficients.");
    // Do not impose a constant kill probability on conservative walks. It adds
    // avoidable heavy tails (and can give unbounded variance in thick bodies).
    double survival = std::min(1.0, weight);
    if (!(survival > 0) || sampler->Get1D() >= survival) return false;
    beta /= survival;
    return true;
  };
  const Atmosphere *atmosphere = scene ? scene->atmosphere : nullptr;
  AtmosphereRay atmosphere_ray(atmosphere);
  bool air_active = false;
  const bool deferred_haze = atmosphere && atmosphere->DeferredHaze();
  const bool sample_haze = atmosphere && atmosphere->SampleHaze();
  random_gen haze_rng = (deferred_haze || sample_haze) ? tracking_rng(sampler) : random_gen(0);
  auto flush_haze = [&]() {
    if (!deferred_haze) return;
    double endpoint_uniform = -1, correction_uniform = -1;
    if (sample_haze) {
      endpoint_uniform = haze_rng.unif_rand();
      correction_uniform = haze_rng.unif_rand();
    }
    auto segment = atmosphere_ray.Flush(endpoint_uniform, correction_uniform);
    RGB contribution;
    for (int c = 0; c < 3; ++c) contribution[c] = segment.radiance[c];
    L += contribution;
    beta *= RGB(segment.transmission);
  };
  auto select_haze = [&](bool enabled, const point3f &p) {
    if (air_active && !enabled) flush_haze();
    atmosphere_ray.Start(p, ray.d, enabled);
    air_active = enabled;
  };


  while (!cancelled(cancel)) {
    const auto *active = state.Active();
    if (active && active->boundary->medium->subsurface_diffusion) {
      stage = "normalized_diffusion";
      if (!diffusion_entry) {
        // A camera moved into this region has no surface entry for the BSSRDF.
        // Terminate this path only; later rays can recover as the camera leaves.
        const PathFailure failure(PathFailureKind::DiffusionInterior,
          "Ray starts in an active subsurface_diffusion() interior without a surface entry; path terminated. Use subsurface() for camera-inside transport.");
        scene->path_diagnostics.Record(failure, input, ray, depth, internal_events,
                                      active->boundary_id, stage);
        break;
      }
      if (depth >= max_depth) break;
      ++depth;
      flush_haze();
      const Medium &medium = *active->boundary->medium;
      // The nonlocal diffusion event is the first non-specular interaction.
      // Its material color is useful to OIDN, but no local shading normal exists.
      if (!wrote_feature) {
        normal = normal3f(0);
        for (int c = 0; c < 3; ++c) albedo[c] = medium.diffusion_color[c];
        wrote_feature = true;
      }
      normal3f outward = geometric_normal(*diffusion_entry);
      if (dot(ray.d, outward) > 0) outward = -outward;
      auto exit = SampleDiffusionSurface(*scene, *active, diffusion_entry->p, outward,
                                        ray.time(), sampler, rng, cancel);
      diffusion_entry.reset();
      if (stats) stats->diffusion_samples.fetch_add(1, std::memory_order_relaxed);
      if (!exit) break; // a missed chord contributes zero, without resampling
      for (int c = 0; c < 3; ++c) beta[c] *= exit->weight[c];
      if (!(beta.Max() > 0)) break;
      const dielectric *outside = exit->outside.ActiveDielectric();
      DiffusionExitBSDF lobe(exit->outward, medium.subsurface_ior,
                             outside ? outside->ref_idx : 1);
      // A glass-owned effective boundary may enter tinted glass. Apply its entry
      // tint exactly once, just as the ordinary priority interface does.
      const auto *outside_medium = exit->outside.Active();
      if (outside && (!outside_medium || !outside_medium->boundary->medium->subsurface))
        beta *= RGB(outside->albedo);
      state = std::move(exit->outside);
      L += direct_light(ray, exit->hit.p, &exit->hit, nullptr, nullptr, state, beta,
                        ru, world, lights, hero, rng, sampler, cancel, nullptr, nullptr, &lobe);
      vec2f u = sampler->Get2D();
      vec3f wi = lobe.Sample(u.xy.x, u.xy.y);
      double pdf = lobe.Pdf(wi), f = lobe.Evaluate(wi);
      if (!(pdf > 0) || !(f > 0)) break;
      beta *= RGB(f / pdf);
      eta_scale /= lobe.EtaSquared();
      rl = ru / pdf;
      previous_light_context = {exit->hit.p, exit->outward, ray.time()};
      specular = false;
      any_diffuse = true;
      ray = spawn(exit->hit, wi, ray.time(), state);
      reconcile_surface_origin(scene, exit->hit, ray, state, cancel);
      if (state.Active() && state.Active()->boundary->medium->subsurface_diffusion)
        diffusion_entry = exit->hit;
      subsurface_flight.reset();
      lighting_origin = ray.o;
      rescale(beta, ru, rl);
      if (depth > roulette_depth) {
        double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
        if (!(survival > 0) || sampler->Get1D() >= survival) break;
        beta /= survival;
      }
      stage = "radiance";
      continue;
    }
    // Find the next geometric endpoint while retaining the atmosphere anchor
    // across straight-through events. A new direction or excluded region resets it.
    if (stats && state.Active() && state.Active()->boundary->medium->subsurface)
      stats->subsurface_intersections.fetch_add(1, std::memory_order_relaxed);
    const bool integrate_haze = integrate_atmosphere(atmosphere, state);
    // In a homogeneous SSS body the free flight is independent of geometry.
    // Draw it first and only search through that distance: a miss now proves a
    // collision, rather than finding a distant surface we will never reach.
    // Search the entire world, including higher-priority glass, nested media,
    // and embedded opaque surfaces. No convexity or isolated-body assumption.
    // Ordinary volumes and diffusion retain their existing query/sampling order.
    std::optional<double> sampled_flight;
    Float query_limit = MaxT;
    if (active && active->boundary->medium->subsurface_accelerated) {
      const Medium &medium = *active->boundary->medium;
      auto proposal = subsurface_flight && flight_boundary == active->boundary_id
                          ? *subsurface_flight : SubsurfaceProposal::Ordinary(medium);
      auto tracker = tracking_rng(sampler);
      double strategy = proposal.guided ? tracker.unif_rand() : 0;
      sampled_flight = proposal.SampleDistance(hero, ray.d, strategy, tracker.unif_rand());
      query_limit = SubsurfaceFlightLimit(ray, *sampled_flight);
      if (stats && query_limit < MaxT)
        stats->subsurface_bounded_queries.fetch_add(1, std::memory_order_relaxed);
    }
    hit_record h;
    bool surface_hit = world->hit(ray, 0, query_limit, h, rng);
    if (!surface_hit && query_limit == MaxT) {
      flush_haze();
      break;
    }
    if (!surface_hit && stats)
      stats->subsurface_bounded_misses.fetch_add(1, std::memory_order_relaxed);
    double distance = surface_hit ? double(h.t) : INFINITY, previous_distance = 0;
    double segment_end = surface_hit ? distance : *sampled_flight;
    HazeIntervalWalk haze_walk(haze_intervals(atmosphere, state, ray, segment_end, cancel));
    select_haze(haze_walk.Initial(), ray.o);
    Float atmosphere_light_pdf = integrate_haze && !specular && use_light_sampling()
                                     ? light_pdf(lights, previous_light_context.p, ray.d, rng, ray.time()) : 0;


    // Between candidates, add clear-air source radiance with the current MIS
    // weights before applying attenuation. Glass absorption advances over the
    // same distance, while clear-air transport follows the selected air regions.
    auto advance = [&](double end) {
      double d = end - previous_distance;
      haze_walk.To(end, [&](bool enabled, double start) {
        select_haze(enabled, ray(Float(start)));
      }, [&](double stop) {
        double denom = (ru + rl * RGB(atmosphere_light_pdf)).Average();
        if (deferred_haze) {
          RGB weight = denom > 0 ? beta / denom : RGB(0);
          atmosphere_ray.Accumulate(ray(Float(stop)), {weight[0], weight[1], weight[2]}, haze_rng.unif_rand());
        } else {
          auto segment = atmosphere_ray.Advance(ray(Float(stop)), sample_haze ? haze_rng.unif_rand() : -1);
          if (denom > 0) L += beta * RGB(segment.radiance) / denom;
          beta *= RGB(segment.transmission);
        }
      });
      beta *= glass_transmittance(state, d);
      previous_distance = end;
    };


    // Process the active medium up to the geometric hit. The callback may leave
    // the direction unchanged, terminate this path, or replace it after scattering.
    bool scattered = false, terminated = false;
    if (const auto *entry = state.Active()) {
      const Medium &medium = *entry->boundary->medium;
      if (medium.subsurface) {
        auto proposal = subsurface_flight && flight_boundary == entry->boundary_id
                            ? *subsurface_flight : SubsurfaceProposal::Ordinary(medium);
        double t;
        if (sampled_flight) t = *sampled_flight;
        else {
          auto tracker = tracking_rng(sampler);
          double strategy = proposal.guided ? tracker.unif_rand() : 0;
          t = proposal.SampleDistance(hero, ray.d, strategy, tracker.unif_rand());
        }
        bool collision = t < distance;
        double end = collision ? t : distance;
        advance(end);
        subsurface_segment(beta, ru, rl, medium, proposal, ray.d, end, collision);
        subsurface_flight.reset();
        if (!(beta.Max() > 0) || !(ru.Max() > 0)) { flush_haze(); break; }
        if (collision) {
          flush_haze();
          ++internal_events;
          if (stats) {
            stats->subsurface_events.fetch_add(1, std::memory_order_relaxed);
            stats->scattering_events.fetch_add(1, std::memory_order_relaxed);
          }
          point3f p;
          for (int a = 0; a < 3; ++a) p[a] = Float(double(ray.o[a]) + double(ray.d[a]) * t);
          if (t > 0 && p[0] == ray.o[0] && p[1] == ray.o[1] && p[2] == ray.o[2]) {
            if (stats) stats->rounded_subsurface_flights.fetch_add(1, std::memory_order_relaxed);
            // Exponentials have support arbitrarily close to zero. An occasional
            // rounded displacement is ordinary position roundoff: retain its
            // sampled distance and density, without resampling or forcing a step.
            // Fail only when even a typical flight cannot move this position.
            double rate = proposal.extinction[hero];
            if (proposal.guided) rate = std::max(rate, proposal.GuideRate(hero, ray.d));
            bool resolved = false;
            for (int a = 0; a < 3; ++a)
              resolved |= Float(double(ray.o[a]) + double(ray.d[a]) / rate) != ray.o[a];
            if (!resolved)
              throw PathFailure(PathFailureKind::PositionPrecision, "Subsurface mean free path is below position precision. Reduce optical thickness or move/rescale the scene near the origin.");
          }
          // The position may round across the boundary even when t rounds below
          // h.t. Use the endpoint and ray-position error bounds, not just t.
          bool adjusted = false;
          if (surface_hit) p = SubsurfaceCollisionPoint(p, ray, t, h, adjusted);
          if (stats && adjusted)
            stats->rounded_subsurface_flights.fetch_add(1, std::memory_order_relaxed);
          proposal = SubsurfaceProposal::Ordinary(medium);
          proposal.wo = -ray.d;
          proposal.guided = medium.subsurface_guided && medium.subsurface_guide_eligible && entry->guide_valid;
          if (proposal.guided) proposal.axis = unit_vector(entry->guide_axis);
          if (stats && medium.subsurface_guided) {
            auto &counter = proposal.guided ? stats->guide_eligible : stats->guide_fallback;
            counter.fetch_add(1, std::memory_order_relaxed);
          }
          L += direct_light(ray, p, nullptr, nullptr, &proposal.phase, state, beta, ru,
                            world, lights, hero, rng, sampler, cancel, &proposal);
          double branch = proposal.guided ? sampler->Get1D() : 0;
          vec2f u = sampler->Get2D();
          vec3f wi = proposal.SampleDirection(hero, branch, u.xy.x, u.xy.y);
          RGB before = ru;
          beta *= RGB(proposal.phase.p(-ray.d, wi));
          for (int c = 0; c < 3; ++c) ru[c] *= proposal.DirectionPdf(c, wi);
          rl = before;
          rescale(beta, ru, rl);
          previous_light_context = {p, normal3f(0), ray.time()};
          ray = Ray(p, wi, ray.time());
          lighting_origin = p;
          state.SetRay(ray);
          subsurface_flight = proposal;
          flight_boundary = entry->boundary_id;
          specular = false;
          any_diffuse = true;
          if (!wrote_feature) {
            normal = normal3f(0);
            for (int c = 0; c < 3; ++c) {
              double extinction = medium.sigma_s[c] + medium.sigma_a[c];
              albedo[c] = extinction > 0 ? medium.sigma_s[c] / extinction : 0;
            }
            wrote_feature = true;
          }
          if (!internal_roulette()) break;
          continue;
        }
      } else {
      subsurface_flight.reset();
      auto tracker = tracking_rng(sampler);
      RGB T = sample_majorant(
          *entry, ray, distance, hero, tracker,
          [&](double t, const MediumProperties &mp, const point3f &m, const RGB &T) {
            advance(t);
            point3f n = null_coefficient(mp, m);
            double proposal = T[hero] * m[hero];
            if (!(proposal > 0)) {
              terminated = true;
              return false;
            }


            // Estimate local medium emission at every candidate before classifying
            // it. Correct the absorption-weighted source for the candidate proposal
            // and RGB density term, independent of the subsequent event choice.
            if (depth < max_depth) {
              // An emitting candidate needs extinction at its own position.
              // Nonemissive null events can keep accumulating cheap weights.
              if ((RGB(mp.sigma_a) * RGB(mp.Le)).Max() > 0) flush_haze();
              RGB re = ru * T * RGB(m) / proposal;
              if (re.Average() > 0)
                L += beta * T * RGB(mp.sigma_a) * RGB(mp.Le) / proposal / re.Average();
            }


            // Thin the hero-channel majorant into absorption, scattering, or the
            // remaining null probability. Absorption ends further transport.
            double mode = tracker.unif_rand(), pa = mp.sigma_a[hero] / m[hero],
                   ps = mp.sigma_s[hero] / m[hero];
            if (mode < pa) {
              terminated = true;
              return false;
            }


            // A real scattering event consumes a bounce and reweights the RGB
            // channels by their scattering coefficients relative to the proposal.
            if (mode < pa + ps) {
              flush_haze();
              if (depth >= max_depth) {
                terminated = true;
                return false;
              }
              ++depth;
              if (stats)
                stats->scattering_events.fetch_add(1, std::memory_order_relaxed);
              double pdf = T[hero] * mp.sigma_s[hero];
              if (!(pdf > 0)) {
                terminated = true;
                return false;
              }
              RGB w = T * RGB(mp.sigma_s) / pdf;
              beta *= w;
              ru *= w;


              // Reconstructed surface positions can lie off the ray by their
              // error bound. Keep a near-endpoint collision on the segment's
              // interior side when converting its double distance to a Float point.
              double tolerance =
                  8 * std::numeric_limits<Float>::epsilon() *
                      std::max({1.0, std::abs(double(ray.o[0])), std::abs(double(ray.o[1])),
                                std::abs(double(ray.o[2])), distance}) +
                  h.pError.length();
              double position_t = distance - t < tolerance ? std::max(0.0, t - tolerance) : t;
              point3f collision;
              for (int a = 0; a < 3; ++a)
                collision[a] = Float(double(ray.o[a]) + double(ray.d[a]) * position_t);
              MediumInteraction interaction{collision, -ray.d, ray.time(), mp};
              point3f p = interaction.p;


              // Connect this vertex to a sampled light, then continue using a
              // phase-function sample. Store its density for MIS at the next
              // emission or atmospheric contribution along the continued path.
              L += direct_light(ray, p, nullptr, nullptr, &interaction.properties.phase, state,
                                beta, ru, world, lights, hero, rng, sampler, cancel);
              vec2f u = sampler->Get2D();
              auto sample = mp.phase.Sample(-ray.d, u.xy.x, u.xy.y);
              beta *= RGB(sample.p / sample.pdf);
              rl = ru / sample.pdf;
              previous_light_context = {p, normal3f(0), ray.time()};
              ray = Ray(p, unit_vector(sample.wi), ray.time());
              lighting_origin = p;
              state.SetRay(ray);
              scattered = true;
              specular = false;
              any_diffuse = true;

              // Volume scattering has no surface normal. Use local single-
              // scattering albedo, independent of illumination and path weight.
              if (!wrote_feature) {
                normal = normal3f(0);
                for (int c = 0; c < 3; ++c) {
                  double extinction = mp.sigma_s[c] + mp.sigma_a[c];
                  albedo[c] = extinction > 0 ? mp.sigma_s[c] / extinction : 0;
                }
                wrote_feature = true;
              }
              return false;
            }


            // A null event preserves direction and bounce depth. Its probability
            // still changes throughput and the two competing path-density terms.
            if (stats)
              stats->null_events.fetch_add(1, std::memory_order_relaxed);
            double pdf = T[hero] * n[hero];
            if (!(pdf > 0)) {
              terminated = true;
              return false;
            }
            RGB w = T * RGB(n) / pdf;
            beta *= w;
            ru *= w;
            rl *= T * RGB(m) / pdf;
            rescale(beta, ru, rl);
            if (!(beta.Max() > 0) || !(ru.Max() > 0)) {
              terminated = true;
              return false;
            }
            return true;
          },
          cancel, stats, integrate_haze);


      // A callback that scattered already installed the new ray. Apply roulette
      // there and start another iteration; only an unscattered path reaches the
      // original geometric endpoint and needs the residual interval correction.
      if (terminated) {
        flush_haze();
        break;
      }
      if (scattered) {
        if (depth > roulette_depth) {
          double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
          if (!(survival > 0) || sampler->Get1D() >= survival)
            break;
          beta /= survival;
        }
        continue;
      }
      if (T[hero] > 0) {
        RGB w = T / T[hero];
        beta *= w;
        ru *= w;
        rl *= w;
      }
      }
    }


    // Complete local transport to a finite hit. The environment's geometric
    // shell is only a tracing endpoint; its atmospheric tail is handled through
    // the infinite radiance query below, not a finite haze segment to that shell.
    if (!h.infinite_area_hit) advance(distance);
    else beta *= glass_transmittance(state, distance - previous_distance);


    // Losing OpenPBR surfaces contribute neither emission nor a scattering
    // event. Classify before emission, just as a physically hidden boundary.
    const auto *pbr = dynamic_cast<const OpenPBRMaterial *>(h.mat_ptr);
    if (pbr && priority_hidden(state, h, ray.d)) {
      state.CrossDielectric(h, ray.d);
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      subsurface_flight.reset();
      continue;
    }

    // Invisible medium boundaries and alpha-mask misses continue the same path
    // without spending a bounce or changing the last real scattering proposal.
    if (h.medium_boundary && !h.medium_boundary->keep_surface) {
      state.Cross(h, ray.d);
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    if (h.alpha_miss) {
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }
    flush_haze();
    bool invisible = false;
    Ray emission_ray = ray;


    // Evaluate infinite emission at the last real lighting vertex or atmospheric
    // anchor. Hidden emitters can be skipped before diffuse/medium scattering.
    if (h.infinite_area_hit) {
      emission_ray = Ray(atmosphere ? atmosphere_ray.Origin(ray.o) : lighting_origin, ray.d, ray.time());
      state.SetRay(emission_ray);
    }
    point3f le = h.mat_ptr ? h.mat_ptr->emitted(emission_ray, h, h.u, h.v, h.p, invisible) : point3f(0);
    if (invisible && !any_diffuse) {
      { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
      continue;
    }


    // A transparent camera background hides distant emission while retaining
    // clear-air haze. Remove haze already integrated along the path before adding
    // the remaining environment contribution with its emission-hit MIS weight.
    if (depth == 0 && h.infinite_area_hit && !(scene && scene->has_media))
      transparency = 1;
    bool hide_background =
        scene && scene->transparent_background && depth == 0 && h.infinite_area_hit;
    if (hide_background && atmosphere)
      le = atmosphere->SkyRadiance(emission_ray.o, emission_ray.d);
    if (atmosphere && h.infinite_area_hit)
      le = atmosphere_ray.Remaining(le);
    if (!hide_background || atmosphere) {
      double denom = ru.Average();
      if (!specular && use_light_sampling()) {
        Float competing_pdf = scene && scene->light_sampler && !atmosphere
            ? scene->light_sampler->EmitterPdf(previous_light_context, ray.d, h, rng)
            : light_pdf(lights, previous_light_context.p, ray.d, rng, ray.time());
        denom = (ru + rl * RGB(competing_pdf)).Average();
      }
      if (denom > 0)
        L += beta * RGB(le) / denom;
    }


    // OpenPBR supplies a jointly sampled layered BSDF, including any discrete
    // thin-wall lobe. The adapter supplies cosine and radiance-mode refraction
    // scaling; applying either again here would darken transmission twice.
    if (pbr) {
      const bool solid = pbr->is_dielectric();
      PriorityInterface interface;
      if (solid) interface = state.Interface(h, ray.d);
      const bool from_inside = solid && !interface.entering;
      if ((!from_inside && depth >= max_depth) || !(beta.Max() > 0) || !(ru.Average() > 0)) break;
      if (from_inside) ++internal_events;
      else ++depth;
      const dielectric *exterior = solid ? (interface.entering ? interface.before : interface.after)
                                         : state.ActiveDielectric();
      auto bsdf = pbr->Prepare(ray, h, exterior ? exterior->ref_idx : 1);
      L += direct_light(ray, h.p, &h, nullptr, nullptr, state, beta, ru, world, lights,
                        hero, rng, sampler, cancel, nullptr, nullptr, nullptr, &bsdf);
      const Float branch = sampler->Get1D();
      const vec2f uv = sampler->Get2D();
      const auto sample = bsdf.Sample(branch, uv[0], uv[1]);
      if (!(sample.pdf > 0) || !(RGB(sample.weight).Max() > 0)) break;
      beta *= RGB(sample.weight);
      if (solid && sample.transmission) {
        state.CrossDielectric(h, sample.direction);
        eta_scale *= sample.eta_squared; // roulette compensation only, not throughput
      }
      if (!sample.specular) {
        rl = ru / sample.pdf;
        previous_light_context = {h.p, h.has_bump ? h.bump_normal : h.normal, ray.time()};
        any_diffuse = true;
        if (!wrote_feature) {
          albedo = pbr->get_albedo(h);
          normal = h.has_bump ? h.bump_normal : h.normal;
          wrote_feature = true;
        }
      }
      specular = sample.specular;
      { Ray next=spawn(h,unit_vector(sample.direction),ray.time(),state);
        if(sample.specular) PropagateRayDifferentials(ray,h,next,sample.transmission,std::sqrt(sample.eta_squared));
        ray=next; }
      reconcile_surface_origin(scene, h, ray, state, cancel);
      subsurface_flight.reset();
      lighting_origin = ray.o;
      rescale(beta, ru, rl);
      if (from_inside && !internal_roulette()) break;
      if (!from_inside && depth > roulette_depth) {
        const double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
        if (!(survival > 0) || sampler->Get1D() >= survival) break;
        beta /= survival;
      }
      continue;
    }

    // Resolve SSS and adjoining glass with the same priority interface. Hidden
    // boundaries update membership without a BSDF, tint, depth event or roulette.
    const Medium *body = subsurface_medium(h);
    if (body && (!h.mat_ptr || !h.mat_ptr->is_dielectric()))
      throw std::runtime_error("Subsurface mesh faces must use the neutral dielectric boundary. Disable imported face materials.");
    std::optional<VolumePathState> diffusion_transmitted_state;
    if (scene && scene->has_diffusion && h.mat_ptr && h.mat_ptr->is_dielectric()) {
      // At exact glass/liquid contact, the closest hit may be the glass face
      // before the liquid has entered the stack. Determine the actual adjacent
      // region before sampling Fresnel, avoiding a fabricated glass/air interface.
      Ray transmitted_probe(OffsetMediumOrigin(h, ray.d), ray.d, ray.time());
      auto adjacent = scene->InitialState(transmitted_probe, cancel);
      const auto *before = state.Active(), *after = adjacent.Active();
      if ((before && before->boundary->medium->subsurface_diffusion) ||
          (after && after->boundary->medium->subsurface_diffusion))
        diffusion_transmitted_state = std::move(adjacent);
    }
    if (cross_matched_dielectric(state, h, ray.d, beta,
                                diffusion_transmitted_state ? &*diffusion_transmitted_state : nullptr)) {
      Ray next = spawn(h, ray.d, ray.time(), state);
      PropagateRayDifferentials(ray, h, next, false, 1, true);
      ray = next;
      reconcile_surface_origin(scene, h, ray, state, cancel);
      if (state.Active() && state.Active()->boundary->medium->subsurface_diffusion)
        diffusion_entry = h;
      subsurface_flight.reset();
      // Do not spend depth or reset specular, lighting_origin, ru/rl, or the
      // previous light context: direct-light sampling also crosses this pane.
      continue;
    }
    if (h.mat_ptr && h.mat_ptr->is_dielectric() &&
        (body || state.ContainsSubsurface() || diffusion_transmitted_state)) {
      auto interface = state.Interface(h, ray.d);
      if (diffusion_transmitted_state)
        interface.after = diffusion_transmitted_state->ActiveDielectric();
      if (interface.Hidden()) {
        if (diffusion_transmitted_state) state = *diffusion_transmitted_state;
        else state.CrossDielectric(h, ray.d);
        { Ray next=spawn(h,ray.d,ray.time(),state);
        PropagateRayDifferentials(ray,h,next,false,1,true); ray=next; }
        reconcile_surface_origin(scene, h, ray, state, cancel);
        if (state.Active() && state.Active()->boundary->medium->subsurface_diffusion)
          diffusion_entry = h;
        subsurface_flight.reset();
        continue;
      }
      bool from_inside = body && !interface.entering;
      if ((!from_inside && depth >= max_depth) || !(beta.Max() > 0) || !(ru.Average() > 0)) break;
      if (from_inside) ++internal_events;
      else ++depth;
      if (stats && body) stats->subsurface_boundaries.fetch_add(1, std::memory_order_relaxed);
      double eta = interface.Eta();
      SubsurfaceBoundaryBSDF bsdf(ray.d, geometric_normal(h), eta, body ? body->subsurface_roughness : 0);
      if (!bsdf.IsSpecular())
        L += direct_light(ray, h.p, &h, nullptr, nullptr, state, beta, ru, world, lights,
                          hero, rng, sampler, cancel, nullptr, &bsdf);
      double branch = sampler->Get1D();
      vec2f u = bsdf.IsSpecular() ? vec2f(0, 0) : sampler->Get2D();
      auto sample = bsdf.Sample(branch, u.xy.x, u.xy.y);
      if (!(sample.weight > 0) || !(sample.pdf > 0)) break;
      beta *= RGB(sample.weight);
      if (!body && interface.entering)
        beta *= RGB(static_cast<const dielectric *>(h.mat_ptr)->albedo);
      if (sample.transmission) {
        eta_scale *= eta * eta;
        if (diffusion_transmitted_state) state = *diffusion_transmitted_state;
        else cross_subsurface(state, h, sample.wi);
      }
      if (!sample.specular) {
        rl = ru / sample.pdf;
        previous_light_context = {h.p, h.geometric_normal, ray.time()};
        any_diffuse = true;
      }
      specular = sample.specular;
      { Ray next=spawn(h,sample.wi,ray.time(),state);
        if(sample.specular) PropagateRayDifferentials(ray,h,next,sample.transmission,Float(eta));
        ray=next; }
      reconcile_surface_origin(scene, h, ray, state, cancel);
      if (state.Active() && state.Active()->boundary->medium->subsurface_diffusion)
        diffusion_entry = h;
      subsurface_flight.reset();
      lighting_origin = ray.o;
      // Perfect reflection/refraction continues to the next feature. A rough
      // dielectric is itself a non-delta glossy surface and supplies its guide.
      if (!wrote_feature && !sample.specular) {
        normal = h.has_bump ? h.bump_normal : h.normal;
        albedo = h.mat_ptr->get_albedo(h);
        wrote_feature = true;
      }
      rescale(beta, ru, rl);
      if (from_inside && !internal_roulette()) break;
      if (!from_inside && depth > roulette_depth) {
        double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
        if (!(survival > 0) || sampler->Get1D() >= survival) break;
        beta /= survival;
      }
      continue;
    }
    subsurface_flight.reset();

    // Emission is allowed at the terminal vertex before enforcing the depth
    // limit. Further surface scattering requires positive throughput and density.
    if (depth >= max_depth || !(beta.Max() > 0) || !(ru.Average() > 0) || !h.mat_ptr)
      break;
    scatter_record s;
    // Dielectric membership uses the oriented geometric normal, not a shading normal.
    hit_record shading_hit = h;
    if (h.mat_ptr->is_dielectric())
      shading_hit.normal = geometric_normal(h);
    if (!h.mat_ptr->scatter(ray, shading_hit, s, sampler))
      break;


    // Keep albedo and normal at the same first non-delta interaction, including
    // surfaces seen through glass or mirrors. Hidden/passthrough hits do not count.
    if (!wrote_feature && !h.mat_ptr->is_delta_specular() && !s.is_passthrough) {
      normal = h.has_bump ? h.bump_normal : h.normal;
      albedo = h.mat_ptr->get_albedo(h);
      wrote_feature = true;
    }
    if (!s.is_passthrough)
      ++depth;


    // Delta reflection/refraction supplies its own direction. Account for the
    // radiance-mode eta^2 factor on transmission and keep a compensating factor
    // for roulette, so temporary changes inside glass do not kill paths too early.
    if (s.is_specular) {
      beta *= RGB(s.attenuation);
      if (s.is_transmission && !s.is_passthrough) {
        double eta2 = double(s.eta) * s.eta;
        beta /= eta2;
        eta_scale *= eta2;
      }
      cross_if_transmitted(state, h, ray.d, s.specular_ray.d);
      { Ray next=spawn(h,unit_vector(s.specular_ray.d),ray.time(),state);
        if(h.mat_ptr->is_delta_specular() || s.is_passthrough)
          PropagateRayDifferentials(ray,shading_hit,next,s.is_transmission,s.eta,s.is_passthrough);
        ray=next; }
      if (!s.is_passthrough)
        specular = true;
    } else {
      // Nondelta surfaces use both light sampling and BSDF continuation. Keep
      // the continuation PDF for the competing strategy at the next vertex.
      L += direct_light(ray, h.p, &h, s.pdf_ptr, nullptr, state, beta, ru, world, lights, hero, rng,
                        sampler, cancel);
      vec3f wi = s.pdf_ptr->generate(sampler, any_diffuse, ray.time());
      if (!(wi.squared_length() > 0))
        break;
      wi = unit_vector(wi);
      Float p = s.pdf_ptr->value(wi, rng, ray.time());
      if (!(p > 0) || !std::isfinite(p))
        break;
      beta *= RGB(h.mat_ptr->f(ray, h, wi)) / p;
      rl = ru / p;
      previous_light_context = {h.p, h.has_bump ? h.bump_normal : h.normal, ray.time()};
      specular = false;
      any_diffuse = true;
      cross_if_transmitted(state, h, ray.d, wi);
      ray = spawn(h, wi, ray.time(), state);
    }


    // Repair membership if the surface offset crossed a coincident boundary,
    // stabilize the RGB ratios, and apply compensated roulette after real bounces.
    reconcile_surface_origin(scene, h, ray, state, cancel);
    if (state.Active() && state.Active()->boundary->medium->subsurface_diffusion)
      diffusion_entry = h;
    if (!s.is_passthrough)
      lighting_origin = ray.o;
    rescale(beta, ru, rl);
    if (!s.is_passthrough && depth > roulette_depth) {
      double survival = std::min(1.0, (beta * RGB(eta_scale) / ru.Average()).Max());
      if (!(survival > 0) || sampler->Get1D() >= survival)
        break;
      beta /= survival;
    }
  }


  } catch (const PathFailure &failure) {
    // Do not retry or renormalize surviving samples. Keep this sample in the
    // estimator, with its accumulated radiance and no further contribution.
    if (!scene) throw;
    scene->path_diagnostics.Record(failure, input, ray, depth, internal_events,
                                  state.Active() ? state.Active()->boundary_id : 0, stage);
  }

  if (stats) {
    if (internal_events) {
      stats->subsurface_event_paths.fetch_add(1, std::memory_order_relaxed);
      stats->total_subsurface_events.fetch_add(internal_events, std::memory_order_relaxed);
      size_t bin = 0;
      while (bin < 63 && internal_events > (uint64_t(1) << bin)) ++bin;
      stats->subsurface_event_histogram[bin].fetch_add(1, std::memory_order_relaxed);
    }
    uint64_t old = stats->max_subsurface_events.load(std::memory_order_relaxed);
    while (old < internal_events && !stats->max_subsurface_events.compare_exchange_weak(
        old, internal_events, std::memory_order_relaxed)) {}
  }
  // Perform the final precision conversion only after all contributions are summed.
  radiance = L.FloatRGB();
}

#ifdef NOT_CRAN
#include "../hitables/box.h"
#include "../materials/texture.h"
#include <testthat.h>
context("Index-matched dielectric connections") {
  test_that("equal active IORs change absorption and tint without hiding the boundary") {
    dielectric outside(point3f(1), 1.5, point3f(.1), 5);
    dielectric pane(point3f(.7, .8, .9), 1.5, point3f(.2, .5, 1), 1);
    VolumePathState state;
    state.glass.push_back(&outside);
    hit_record h;
    h.mat_ptr = &pane;
    h.normal = h.geometric_normal = normal3f(0, 0, 1);
    RGB weight(1);
    expect_true(cross_matched_dielectric(state, h, vec3f(0, 0, -1), weight));
    expect_true(state.ActiveDielectric() == &pane);
    weight *= glass_transmittance(state, 2);
    expect_true(cross_matched_dielectric(state, h, vec3f(0, 0, 1), weight));
    expect_true(state.ActiveDielectric() == &outside);
    expect_true(state.glass.size() == 1);
    for (int c = 0; c < 3; ++c)
      expect_true(std::abs(weight[c] - pane.albedo[c] * std::exp(-2. * pane.attenuation[c])) < 1e-7);
    expect_true(opaque_shadow_material(&pane) == OpaqueShadowType::Unsupported);
  }
  test_that("priority-hidden glass crosses without tint or absorption changes") {
    dielectric winner(point3f(1), 1.3, point3f(.2), 0);
    dielectric hidden(point3f(0), 1.8, point3f(100), 2);
    VolumePathState state;
    state.glass.push_back(&winner);
    hit_record h;
    h.mat_ptr = &hidden;
    h.normal = h.geometric_normal = normal3f(0, 0, 1);
    RGB weight(1);
    expect_true(cross_matched_dielectric(state, h, vec3f(0, 0, -1), weight));
    expect_true(state.glass.size() == 2);
    expect_true(state.ActiveDielectric() == &winner);
    expect_true(cross_matched_dielectric(state, h, vec3f(0, 0, 1), weight));
    expect_true(state.glass.size() == 1);
    expect_true(weight.Average() == 1);
  }
  test_that("real mismatches and layered materials are not straight-through filters") {
    VolumePathState state;
    dielectric pane(point3f(1), Float(1.0001), point3f(0), 0);
    hit_record h;
    h.mat_ptr = &pane;
    h.normal = h.geometric_normal = normal3f(0, 0, 1);
    RGB weight(1);
    expect_false(cross_matched_dielectric(state, h, vec3f(0, 0, -1), weight));
    expect_true(state.glass.empty());

    Rcpp::Function constructor = Rcpp::Environment::namespace_env("rayrender")["openpbr"];
    Rcpp::List materials = constructor();
    Rcpp::List descriptor = materials[0];
    Rcpp::List parameters = Rcpp::clone(Rcpp::as<Rcpp::List>(descriptor["openpbr"]));
    parameters["specular_ior"] = 1.;
    parameters["transmission_weight"] = 1.;
    parameters["coat_weight"] = .7;
    OpenPBRMaterial layered(parameters, std::make_shared<constant_texture>(point3f(1)), nullptr, false);
    h.mat_ptr = &layered;
    expect_true(layered.is_dielectric());
    expect_false(cross_matched_dielectric(state, h, vec3f(0, 0, -1), weight));
    expect_true(state.glass.empty());
    expect_true(weight.Average() == 1);
  }
}
context("Accelerated subsurface arithmetic") {
  test_that("ordinary collision products agree with log-space weights and retain extreme fallbacks") {
    Rcpp::NumericMatrix transform(4, 4);
    for (int i = 0; i < 4; ++i) transform(i, i) = 1;
    Medium medium(Rcpp::List::create(
        Rcpp::Named("sigma_a") = Rcpp::NumericVector::create(0, .01, 20),
        Rcpp::Named("sigma_s") = Rcpp::NumericVector::create(0, 80, .2),
        Rcpp::Named("density_scale") = 1, Rcpp::Named("g") = 0,
        Rcpp::Named("emission") = Rcpp::NumericVector::create(0, 0, 0),
        Rcpp::Named("temperature") = R_NilValue, Rcpp::Named("emission_scale") = 1,
        Rcpp::Named("temperature_scale") = 1, Rcpp::Named("temperature_offset") = 0,
        Rcpp::Named("medium_transform") = transform));
    auto proposal = SubsurfaceProposal::Ordinary(medium);
    for (bool guided : {false, true}) {
      proposal.guided = guided;
      for (bool collision : {false, true}) {
        for (double distance : {0., .001, .1, .5, 1., 10000.}) {
          for (double weight : {0., 1e-100, 1e-80, .01, 1., 1e80, 1e100}) {
            RGB beta(weight), ru(.3), rl(.7);
            beta[2] *= .37;
            ru[0] = 0;
            RGB reference_beta = beta, reference_ru = ru, reference_rl = rl;
            medium.subsurface_accelerated = false;
            subsurface_segment(reference_beta, reference_ru, reference_rl,
                               medium, proposal, vec3f(0, 0, 1), distance, collision);
            medium.subsurface_accelerated = true;
            subsurface_segment(beta, ru, rl, medium, proposal, vec3f(0, 0, 1), distance, collision);
            for (int c = 0; c < 3; ++c) {
              expect_true(std::abs(beta[c] - reference_beta[c]) < 2e-12);
              expect_true(std::abs(ru[c] - reference_ru[c]) < 2e-12);
              expect_true(std::abs(rl[c] - reference_rl[c]) < 2e-12);
            }
          }
        }
      }
    }
  }
}
context("Radiance recovery") {
  test_that("invalid contributions cannot partially overwrite accumulated light") {
    for (double invalid : {double(NAN), double(INFINITY), double(std::numeric_limits<Float>::max()) * 2}) {
      RGB accumulated(point3f(1, 2, 3)), contribution(4);
      contribution[2] = invalid;
      bool rejected = false;
      try { accumulated += contribution; }
      catch (const PathFailure &failure) {
        rejected = failure.kind == PathFailureKind::Radiance;
      }
      expect_true(rejected);
      expect_true((accumulated[0] == 1 && accumulated[1] == 2 && accumulated[2] == 3));
    }
  }
}
context("Surface origins at perpendicular medium boundaries") {
  test_that("a horizontal surface offset reconciles a nearby horizontal medium cap") {
    Transform identity;
    Rcpp::NumericMatrix transform(4, 4);
    for (int i = 0; i < 4; ++i) transform(i, i) = 1;
    auto medium = std::make_shared<Medium>(Rcpp::List::create(
        Rcpp::Named("sigma_a") = Rcpp::NumericVector::create(.1, .1, .1),
        Rcpp::Named("sigma_s") = Rcpp::NumericVector::create(0, 0, 0),
        Rcpp::Named("density_scale") = 1, Rcpp::Named("g") = 0,
        Rcpp::Named("emission") = Rcpp::NumericVector::create(0, 0, 0),
        Rcpp::Named("temperature") = R_NilValue, Rcpp::Named("emission_scale") = 1,
        Rcpp::Named("temperature_scale") = 1, Rcpp::Named("temperature_offset") = 0,
        Rcpp::Named("medium_transform") = transform));
    auto mat = std::make_shared<diffuse_material>(std::make_shared<constant_texture>(point3f(1)));
    auto geometry = std::make_shared<box>(vec3f(-2, -2, -2), vec3f(2, 0, 2),
                                         mat, nullptr, nullptr, &identity, &identity, false);
    VolumeScene scene;
    scene.boundaries.add(std::make_shared<MediumBoundary>(geometry, medium, identity, false,
                                                         scene.NextBoundaryId()));
    scene.Finish(0, 1);
    const Float epsilon = std::numeric_limits<Float>::epsilon();
    for (Float height : {-epsilon, Float(0), epsilon}) {
      for (Float vertical : {Float(-1), Float(1)}) {
        hit_record surface;
        surface.p = point3f(0, height, 0);
        surface.pError = vec3f(epsilon, 0, epsilon);
        Ray ray(point3f(epsilon, height, 0), vec3f(0, vertical, 0));
        VolumePathState state;
        reconcile_surface_origin(&scene, surface, ray, state, nullptr);
        const bool inside = height < 0 || (height == 0 && vertical > 0);
        expect_true((!state.media.empty()) == inside);
        expect_true((ray.medium != nullptr) == inside);
      }
    }
    // Away from contact, do not silently repair an invalid incremental state.
    hit_record away;
    away.p = point3f(0, -.1, 0);
    away.pError = vec3f(epsilon, 0, epsilon);
    Ray ray(point3f(epsilon, -.1, 0), vec3f(0, 1, 0));
    VolumePathState state;
    reconcile_surface_origin(&scene, away, ray, state, nullptr);
    expect_true(state.media.empty());
  }
}
#endif
