# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

render_scene_rcpp <- function(camera_info, ambient_light, type, radius, shape, position_list, properties, velocity, moving, n, bghigh, bglow, ischeckered, checkercolors, gradient_info, noise, isnoise, noisephase, noiseintensity, noisecolorlist, angle, isimage, filelocation, alphalist, lightintensity, isflipped, isvolume, voldensity, implicit_sample, order_rotation_list, clampval, isgrouped, group_pivot, group_translate, group_angle, group_order_rotation, group_scale, tri_normal_bools, is_tri_color, tri_color_vert, fileinfo, filebasedir, progress_bar, numbercores, hasbackground, background, scale_list, sigmavec, rotate_env, verbose, debug_channel, shared_id_mat, is_shared_mat, min_variance, min_adaptive_size) {
    .Call(`_rayrender_render_scene_rcpp`, camera_info, ambient_light, type, radius, shape, position_list, properties, velocity, moving, n, bghigh, bglow, ischeckered, checkercolors, gradient_info, noise, isnoise, noisephase, noiseintensity, noisecolorlist, angle, isimage, filelocation, alphalist, lightintensity, isflipped, isvolume, voldensity, implicit_sample, order_rotation_list, clampval, isgrouped, group_pivot, group_translate, group_angle, group_order_rotation, group_scale, tri_normal_bools, is_tri_color, tri_color_vert, fileinfo, filebasedir, progress_bar, numbercores, hasbackground, background, scale_list, sigmavec, rotate_env, verbose, debug_channel, shared_id_mat, is_shared_mat, min_variance, min_adaptive_size)
}

tonemap_image <- function(nx, ny, routput, goutput, boutput, toneval) {
    .Call(`_rayrender_tonemap_image`, nx, ny, routput, goutput, boutput, toneval)
}

