# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

has_gui_capability <- function() {
    .Call(`_rayrender_has_gui_capability`)
}

render_animation_rcpp <- function(camera_info, scene_info, camera_movement, start_frame, end_frame, filenames, post_process_frame, toneval, bloom, write_image) {
    invisible(.Call(`_rayrender_render_animation_rcpp`, camera_info, scene_info, camera_movement, start_frame, end_frame, filenames, post_process_frame, toneval, bloom, write_image))
}

render_scene_rcpp <- function(camera_info, scene_info) {
    .Call(`_rayrender_render_scene_rcpp`, camera_info, scene_info)
}

PrintClassSizes <- function() {
    invisible(.Call(`_rayrender_PrintClassSizes`))
}

tonemap_image <- function(routput, goutput, boutput, toneval) {
    .Call(`_rayrender_tonemap_image`, routput, goutput, boutput, toneval)
}

