#' Location and Time Sky Light
#' @md
#'
#' @description
#' Creates an infinite light from a sky generated by
#' `skymodelr::generate_sky_latlong()`. Add it to a scene with
#' [add_infinite_light()]. The sky is generated before rendering and cached as
#' an EXR for reuse by still renders, animation frames, and interactive preview.
#'
#' @param lat Latitude in degrees, between -90 and 90.
#' @param long Longitude in degrees, between -180 and 180.
#' @param datetime A single `POSIXct` date and time. Specify its time zone when
#' constructing it with `as.POSIXct()`.
#' @param sky_args Default `list()`. Named arguments passed to
#' `skymodelr::generate_sky_latlong()`, such as `list(hosek = FALSE)` for the
#' Prague model, `resolution`, `altitude`, `moon`, or `stars`. Location, datetime,
#' and the generated filename are supplied by this light and cannot be overridden.
#' @param intensity Default `1`. Nonnegative multiplier for this light's radiance.
#' @param rotation Default `0`. Additional rotation in degrees around the world
#' Y axis, using the same convention as [infinite_light()].
#' @param name Default `"sky"`. Unique light name within the scene.
#'
#' @details Requires the optional skymodelr package. Install any required Prague
#' datasets with `skymodelr::download_sky_data()` before rendering.
#'
#' This is a static image-based sky: `sky_args$altitude` selects one observer
#' altitude for the entire environment. It does not yet evaluate atmospheric
#' radiance at each shading point or advance datetime during an animation.
#' The image uses skymodelr's orientation: north at the image seam, east one
#' quarter across. With zero rotation, north is world +Z and east is world -X.
#' Other infinite lights add to the sky. Use `auto_exposure = TRUE` in
#' [render_scene()] when appropriate for the sky's physical radiance scale.
#'
#' @return A `ray_infinite_light` object containing the sky description.
#' @export
#' @examplesIf interactive() || identical(Sys.getenv("IN_PKGDOWN"), "true")
#' if (requireNamespace("skymodelr", quietly = TRUE)) {
#'   scene = sphere(material = diffuse(color = "white")) |>
#'     add_infinite_light(sky_light(
#'       lat = 40.7, long = -74,
#'       datetime = as.POSIXct("2026-06-21 18:00:00", tz = "America/New_York"),
#'       sky_args = list(resolution = 256)
#'     )) |>
#'     add_camera(camera(aperture = 0))
#'   render_scene(scene, integrator_type = "nee", auto_exposure = TRUE)
#' }
sky_light = function(
  lat,
  long,
  datetime,
  sky_args = list(),
  intensity = 1,
  rotation = 0,
  name = "sky"
) {
  result = structure(
    list(
      type = "sky",
      lat = lat,
      long = long,
      datetime = datetime,
      sky_args = sky_args,
      intensity = intensity,
      rotation = rotation,
      name = name
    ),
    class = "ray_infinite_light"
  )
  validate_infinite_light(result)
  result
}

#' @keywords internal
validate_sky_light = function(light) {
  for (field in c("lat", "long")) {
    value = light[[field]]
    limit = if (field == "lat") 90 else 180
    if (
      !is.numeric(value) ||
        length(value) != 1 ||
        !is.finite(value) ||
        abs(value) > limit
    ) {
      stop(
        "Sky light ",
        field,
        " must be a finite number between -",
        limit,
        " and ",
        limit,
        ".",
        call. = FALSE
      )
    }
  }
  if (
    !inherits(light$datetime, "POSIXct") ||
      length(light$datetime) != 1 ||
      !is.finite(as.numeric(light$datetime))
  ) {
    stop(
      "Sky light datetime must be one finite POSIXct date and time.",
      call. = FALSE
    )
  }
  args = light$sky_args
  if (
    !is.list(args) ||
      (length(args) &&
        (is.null(names(args)) ||
          anyNA(names(args)) ||
          any(!nzchar(names(args))) ||
          anyDuplicated(names(args))))
  ) {
    stop("sky_args must be a uniquely named list.", call. = FALSE)
  }
  reserved = intersect(
    names(args),
    c("lat", "lon", "long", "datetime", "filename", "allow_download")
  )
  if (length(reserved)) {
    stop(
      "sky_args cannot override: ",
      paste(reserved, collapse = ", "),
      ".",
      call. = FALSE
    )
  }
  invisible(TRUE)
}

#' @keywords internal
prepare_infinite_light = function(light) {
  validate_infinite_light(light)
  if (light$type %in% c("image", "disk")) {
    return(light)
  }
  if (light$type %in% c("sun", "moon")) {
    return(prepare_celestial_light(light))
  }
  if (!requireNamespace("skymodelr", quietly = TRUE)) {
    stop(
      "sky_light() requires skymodelr. Install it with install.packages('skymodelr').",
      call. = FALSE
    )
  }
  args = c(
    list(lat = light$lat, lon = light$long, datetime = light$datetime),
    light$sky_args
  )
  supported = names(formals(skymodelr::generate_sky_latlong))
  unknown = setdiff(names(args), supported)
  if (length(unknown) && !"..." %in% supported) {
    stop(
      "Unsupported sky_args: ",
      paste(unknown, collapse = ", "),
      ".",
      call. = FALSE
    )
  }
  if ("allow_download" %in% supported) {
    args$allow_download = FALSE
  }
  cache = file.path(tempdir(), "rayrender-skies")
  dir.create(cache, showWarnings = FALSE)
  key_file = tempfile(tmpdir = cache)
  on.exit(unlink(key_file), add = TRUE)
  saveRDS(
    list(
      args = args,
      version = as.character(utils::packageVersion("skymodelr"))
    ),
    key_file,
    version = 2
  )
  filename = file.path(cache, paste0(unname(tools::md5sum(key_file)), ".exr"))
  if (!file.exists(filename)) {
    success = FALSE
    on.exit(if (!success) unlink(filename), add = TRUE)
    args$filename = filename
    do.call(skymodelr::generate_sky_latlong, args)
    success = TRUE
  }
  infinite_light(
    filename,
    intensity = light$intensity,
    rotation = light$rotation,
    name = light$name
  )
}
