on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: "${{ matrix.config.os }} R: (${{ matrix.config.r }}, OIDN: ${{ matrix.config.oidn }}, RAY_COLOR_DEBUG: ${{ matrix.config.ray_color_debug || 'false' }})"

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release', oidn: 'false'}
          - {os: macos-latest,   r: 'release', oidn: 'true'}
          - {os: macos-latest,   r: 'release', oidn: 'false', ray_color_debug: 'true'}
          - {os: windows-latest, r: 'release', oidn: 'false'}
          - {os: windows-latest, r: 'release', oidn: 'true'}
          - {os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release', oidn: 'false'}
          - {os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release', oidn: 'true'}
          - {os: ubuntu-latest,  r: 'release', oidn: 'false'}  
          - {os: ubuntu-latest,  r: 'release', oidn: 'true'}  
          - {os: ubuntu-latest,  r: 'oldrel-1', oidn: 'false'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true
      IS_GHA: true

    steps:
      - name: Set RGL_USE_NULL for Ubuntu
        if: runner.os == 'Linux'
        run: echo "RGL_USE_NULL=TRUE" >> $GITHUB_ENV

      - name: Set RGL_USE_NULL for macOS
        if: runner.os == 'macOS'
        run: echo "RGL_USE_NULL=TRUE" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install OIDN (macOS)
        if: runner.os == 'macOS' && matrix.config.oidn == 'true'
        run: |
          ARCH=$(uname -m)
          cd $RUNNER_TEMP
          if [ "${ARCH}" = "arm64" ]; then
            curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.arm64.macos.tar.gz
            tar xzf oidn-2.3.1.arm64.macos.tar.gz
            echo "OIDN_PATH=$(pwd)/oidn-2.3.1.arm64.macos" >> $GITHUB_ENV
          else
            curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.x86_64.macos.tar.gz
            tar xzf oidn-2.3.1.x86_64.macos.tar.gz
            echo "OIDN_PATH=$(pwd)/oidn-2.3.1.x86_64.macos" >> $GITHUB_ENV
          fi

      - name: Install OIDN (Linux)
        if: runner.os == 'Linux' && matrix.config.oidn == 'true'
        run: |
          cd $RUNNER_TEMP
          curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.x86_64.linux.tar.gz
          tar xzf oidn-2.3.1.x86_64.linux.tar.gz
          echo "OIDN_PATH=$(pwd)/oidn-2.3.1.x86_64.linux" >> $GITHUB_ENV

      - name: Install OIDN (Windows)
        if: runner.os == 'Windows' && matrix.config.oidn == 'true'
        run: |
          cd $RUNNER_TEMP
          curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.x64.windows.zip
          7z x oidn-2.3.1.x64.windows.zip
          echo "OIDN_PATH=$(pwd)/oidn-2.3.1.x64.windows" >> $GITHUB_ENV

      - name: Set color debugging env + single core
        if: matrix.config.ray_color_debug == 'true'
        run: |
          echo 'options(cores=1)' >> ~/.Rprofile
          echo "RAY_COLOR_DEBUG=true" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
  
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: c("--no-manual","--compact-vignettes=gs+qpdf")

      - name: Upload check logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Make the artifact name unique per OS + R + debug status
          name: "check-logs-${{ matrix.config.os }}-${{ matrix.config.r }}-${{ matrix.config.ray_color_debug }}"
          path: |
            **/*.Rcheck/00install.out
            **/*.Rcheck/00check.log
          if-no-files-found: ignore