on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, OIDN: ${{ matrix.config.oidn }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release', oidn: 'false'}
          - {os: macos-latest,   r: 'release', oidn: 'true'}
          - {os: windows-latest, r: 'release', oidn: 'false'}
          - {os: windows-latest, r: 'release', oidn: 'true'}
          - {os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release', oidn: 'false'}
          - {os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release', oidn: 'true'}
          - {os: ubuntu-latest,  r: 'release', oidn: 'false'}  
          - {os: ubuntu-latest,  r: 'release', oidn: 'true'}  
          - {os: ubuntu-latest,  r: 'oldrel-1', oidn: 'false'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true
      IS_GHA: true

    steps:
      - name: Set RGL_USE_NULL for Ubuntu
        if: runner.os == 'Linux'
        run: echo "RGL_USE_NULL=TRUE" >> $GITHUB_ENV

      - name: Set RGL_USE_NULL for macOS
        if: runner.os == 'macOS'
        run: echo "RGL_USE_NULL=TRUE" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          upload-snapshots: true
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # Install OIDN only if oidn == 'true'
      - name: Install OIDN (macOS)
        if: runner.os == 'macOS' && matrix.config.oidn == 'true'
        run: |
          ARCH=$(uname -m)
          if [ "${ARCH}" = "arm64" ]; then
            curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.arm64.macos.tar.gz
            tar xzf oidn-2.3.1.arm64.macos.tar.gz
            echo "OIDN_PATH=$(pwd)/oidn-2.3.1.arm64.macos" >> $GITHUB_ENV
          else
            curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.x86_64.macos.tar.gz
            tar xzf oidn-2.3.1.x86_64.macos.tar.gz
            echo "OIDN_PATH=$(pwd)/oidn-2.3.1.x86_64.macos" >> $GITHUB_ENV
          fi

      - name: Install OIDN (Linux)
        if: runner.os == 'Linux' && matrix.config.oidn == 'true'
        run: |
          curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.x86_64.linux.tar.gz
          tar xzf oidn-2.3.1.x86_64.linux.tar.gz
          echo "OIDN_PATH=$(pwd)/oidn-2.3.1.x86_64.linux" >> $GITHUB_ENV

      - name: Install OIDN (Windows)
        if: runner.os == 'Windows' && matrix.config.oidn == 'true'
        run: |
          curl -LO https://github.com/OpenImageDenoise/oidn/releases/download/v2.3.1/oidn-2.3.1.x64.windows.zip
          7z x oidn-2.3.1.x64.windows.zip
          echo "OIDN_PATH=$(pwd)/oidn-2.3.1.x64.windows" >> $GITHUB_ENV

      - name: Install rayshader
        run: |
          Rscript -e "if(!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
          Rscript -e "remotes::install_github('tylermorganwall/rayshader')"
          Rscript -e "install.packages('testthat')"

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
